# **ACDC In-Domain Training — YOLOv11s**

*   Training YOLOv11s using COCO pretrained weights
*   Evaluating the trained model on the global ACDC
*   Performing weather-specific evaluations on fog, rain, and snow subsets

### **Mount drive**

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

### **Install Ultralytics**

In [ ]:
!pip install -q ultralytics

### **Import librairies**

In [ ]:
from pathlib import Path
import pandas as pd
import json
import yaml
import torch
import time
import cv2
import numpy as np
from ultralytics import YOLO

### **Path configuration & check GPU**

In [ ]:

PROJECT_ROOT = Path("/content/drive/MyDrive/Dissertation")

YOLO_ROOT = PROJECT_ROOT / "Datasets/processed/acdc_yolo"
RUNS_ROOT = PROJECT_ROOT / "Runs/yolo"

ACDC_YAML = YOLO_ROOT / "acdc.yaml"

print("YOLO_ROOT exists:", YOLO_ROOT.exists())
print("ACDC YAML exists:", ACDC_YAML.exists())
print("CUDA available:", torch.cuda.is_available())
print("GPU:", torch.cuda.get_device_name(0) if torch.cuda.is_available() else "CPU")

YOLO_ROOT exists: True
ACDC YAML exists: True
CUDA available: True
GPU: NVIDIA A100-SXM4-40GB

### **Classes & random seed**

In [ ]:
CLASS_NAMES = [
    "person",
    "bicycle",
    "car",
    "motorcycle",
    "bus",
    "truck"
]

RANDOM_SEED = 42

### **Check dataset folders**

In [ ]:
for split in ["train", "val", "test", "test_fog", "test_rain", "test_snow"]:
    img_dir = YOLO_ROOT / "images" / split
    label_dir = YOLO_ROOT / "labels" / split

    print(f"\n{split}")
    print("images:", img_dir.exists(), len(list(img_dir.glob("*"))) if img_dir.exists() else 0)
    print("labels:", label_dir.exists(), len(list(label_dir.glob("*"))) if label_dir.exists() else 0)

train
images: True 1620
labels: True 1620

val
images: True 540
labels: True 540

test
images: True 540
labels: True 540

test_fog
images: True 100
labels: True 100

test_rain
images: True 340
labels: True 340

test_snow
images: True 100
labels: True 100

### **Training**

In [ ]:
model = YOLO("yolo11s.pt")

train_results = model.train(
    data=str(ACDC_YAML),
    epochs=100,
    imgsz=640,
    batch=16,
    patience=10,
    seed=RANDOM_SEED,
    deterministic=True,
    pretrained=True,
    project=str(RUNS_ROOT),
    name="acdc_in_domain_yolo11s_seed42",
    exist_ok=True,
    plots=True
)

Ultralytics 8.4.50 🚀 Python-3.12.13 torch-2.10.0+cu128 CUDA:0 (NVIDIA A100-SXM4-40GB, 40441MiB)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=16, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/content/drive/MyDrive/Dissertation/Datasets/processed/acdc_yolo/acdc.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=100, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolo11s.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=acdc_in_domain_yolo11s_seed42, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=10, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=/content/drive/MyDrive/Dissertation/Runs/yolo, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/content/drive/.shortcut-targets-by-id/17lufoiYQdFrVMwNFeK91HKX-sBA0zN4V/Dissertation/Runs/yolo/acdc_in_domain_yolo11s_seed42, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=42, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=6

                   from  n    params  module                                       arguments
  0                  -1  1       928  ultralytics.nn.modules.conv.Conv             [3, 32, 3, 2]
  1                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  2                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]
  3                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
  4                  -1  1    103360  ultralytics.nn.modules.block.C3k2            [128, 256, 1, False, 0.25]
  5                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
  6                  -1  1    346112  ultralytics.nn.modules.block.C3k2            [256, 256, 1, True]
  7                  -1  1   1180672  ultralytics.nn.modules.conv.Conv             [256, 512, 3, 2]
  8                  -1  1   1380352  ultralytics.nn.modules.block.C3k2            [512, 512, 1, True]
  9                  -1  1    656896  ultralytics.nn.modules.block.SPPF            [512, 512, 5]
 10                  -1  1    990976  ultralytics.nn.modules.block.C2PSA           [512, 512, 1]
 11                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 12             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 13                  -1  1    443776  ultralytics.nn.modules.block.C3k2            [768, 256, 1, False]
 14                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 15             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  1    127680  ultralytics.nn.modules.block.C3k2            [512, 128, 1, False]
 17                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 18            [-1, 13]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 19                  -1  1    345472  ultralytics.nn.modules.block.C3k2            [384, 256, 1, False]
 20                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 21            [-1, 10]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 22                  -1  1   1511424  ultralytics.nn.modules.block.C3k2            [768, 512, 1, True]
 23        [16, 19, 22]  1    821730  ultralytics.nn.modules.head.Detect           [6, 16, None, [128, 256, 512]]
YOLO11s summary: 182 layers, 9,430,114 parameters, 9,430,098 gradients, 21.6 GFLOPs

Transferred 493/499 items from pretrained weights
Freezing layer 'model.23.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.5±0.1 ms, read: 225.1±71.0 MB/s, size: 455.7 KB)
train: Scanning /content/drive/.shortcut-targets-by-id/17lufoiYQdFrVMwNFeK91HKX-sBA0zN4V/Dissertation/Datasets/processed/acdc_yolo/labels/train... 1620 images, 29 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1620/1620 15.9it/s 1:42
train: New cache created: /content/drive/.shortcut-targets-by-id/17lufoiYQdFrVMwNFeK91HKX-sBA0zN4V/Dissertation/Datasets/processed/acdc_yolo/labels/train.cache
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.8±0.1 ms, read: 0.3±0.2 MB/s, size: 355.2 KB)
val: Scanning /content/drive/.shortcut-targets-by-id/17lufoiYQdFrVMwNFeK91HKX-sBA0zN4V/Dissertation/Datasets/processed/acdc_yolo/labels/val... 540 images, 5 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 540/540 6.9it/s 1:18
val: New cache created: /content/drive/.shortcut-targets-by-id/17lufoiYQdFrVMwNFeK91HKX-sBA0zN4V/Dissertation/Datasets/processed/acdc_yolo/labels/val.cache
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.001, momentum=0.9) with parameter groups 81 weight(decay=0.0), 88 weight(decay=0.0005), 87 bias(decay=0.0)
Plotting labels to /content/drive/.shortcut-targets-by-id/17lufoiYQdFrVMwNFeK91HKX-sBA0zN4V/Dissertation/Runs/yolo/acdc_in_domain_yolo11s_seed42/labels.jpg...
Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /content/drive/.shortcut-targets-by-id/17lufoiYQdFrVMwNFeK91HKX-sBA0zN4V/Dissertation/Runs/yolo/acdc_in_domain_yolo11s_seed42
Starting training for 100 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      1/100      4.04G      1.352      1.521     0.9922         40        640: 100% ━━━━━━━━━━━━ 102/102 2.4it/s 43.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 17/17 1.9it/s 9.1s
                   all        540       3333      0.404      0.278      0.265       0.15

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      2/100      4.06G      1.419      1.177      1.023         52        640: 100% ━━━━━━━━━━━━ 102/102 8.0it/s 12.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 17/17 6.9it/s 2.5s
                   all        540       3333      0.405       0.27      0.253      0.139

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      3/100      4.18G      1.466      1.145      1.039         39        640: 100% ━━━━━━━━━━━━ 102/102 8.2it/s 12.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 17/17 7.2it/s 2.4s
                   all        540       3333      0.428      0.259       0.26      0.142

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      4/100      4.18G      1.462      1.114      1.044         59        640: 100% ━━━━━━━━━━━━ 102/102 8.5it/s 11.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 17/17 5.9it/s 2.9s
                   all        540       3333      0.473      0.258      0.273      0.145

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      5/100      4.18G      1.452      1.103      1.049         53        640: 100% ━━━━━━━━━━━━ 102/102 8.3it/s 12.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 17/17 7.0it/s 2.4s
                   all        540       3333       0.49      0.279      0.288      0.162

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      6/100      4.18G      1.393      1.035      1.029         52        640: 100% ━━━━━━━━━━━━ 102/102 8.8it/s 11.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 17/17 5.8it/s 2.9s
                   all        540       3333      0.455      0.311      0.317      0.177

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      7/100      4.18G        1.4      1.032      1.015         30        640: 100% ━━━━━━━━━━━━ 102/102 8.5it/s 11.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 17/17 5.8it/s 2.9s
                   all        540       3333      0.471      0.305      0.323      0.182

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      8/100      4.18G      1.378     0.9998       1.01         40        640: 100% ━━━━━━━━━━━━ 102/102 8.5it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 17/17 5.6it/s 3.1s
                   all        540       3333       0.45      0.362      0.357      0.198

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      9/100      4.18G      1.362     0.9854      1.008         24        640: 100% ━━━━━━━━━━━━ 102/102 8.6it/s 11.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 17/17 5.7it/s 3.0s
                   all        540       3333      0.537      0.303      0.321      0.176

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     10/100      4.18G      1.346     0.9766      1.008         36        640: 100% ━━━━━━━━━━━━ 102/102 8.4it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 17/17 6.8it/s 2.5s
                   all        540       3333      0.479      0.325      0.323      0.177

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     11/100      4.18G      1.333     0.9427     0.9927         56        640: 100% ━━━━━━━━━━━━ 102/102 8.3it/s 12.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 17/17 6.7it/s 2.5s
                   all        540       3333      0.447      0.333      0.335      0.187

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     12/100      4.18G      1.296     0.9261     0.9798         39        640: 100% ━━━━━━━━━━━━ 102/102 8.3it/s 12.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 17/17 6.7it/s 2.5s
                   all        540       3333      0.582      0.322      0.362      0.212

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     13/100      4.18G      1.286     0.9079      0.985         25        640: 100% ━━━━━━━━━━━━ 102/102 8.4it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 17/17 5.7it/s 3.0s
                   all        540       3333      0.545      0.353      0.379      0.221

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     14/100      4.18G      1.302     0.9159     0.9897         35        640: 100% ━━━━━━━━━━━━ 102/102 8.9it/s 11.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 17/17 5.8it/s 2.9s
                   all        540       3333       0.57      0.347      0.384      0.222

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     15/100      4.18G      1.251       0.87     0.9714         52        640: 100% ━━━━━━━━━━━━ 102/102 8.4it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 17/17 5.8it/s 2.9s
                   all        540       3333        0.6       0.36      0.397      0.227

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     16/100      4.18G      1.291     0.8936     0.9821         55        640: 100% ━━━━━━━━━━━━ 102/102 8.5it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 17/17 5.8it/s 2.9s
                   all        540       3333      0.627      0.351      0.373      0.213

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     17/100      4.18G      1.234     0.8498     0.9609         14        640: 100% ━━━━━━━━━━━━ 102/102 8.1it/s 12.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 17/17 7.4it/s 2.3s
                   all        540       3333      0.519      0.372       0.39      0.226

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     18/100      4.18G      1.222     0.8462     0.9601         30        640: 100% ━━━━━━━━━━━━ 102/102 8.2it/s 12.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 17/17 7.4it/s 2.3s
                   all        540       3333      0.572      0.406      0.413      0.238

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     19/100      4.18G      1.237     0.8493      0.963         25        640: 100% ━━━━━━━━━━━━ 102/102 8.5it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 17/17 5.7it/s 3.0s
                   all        540       3333       0.57      0.357      0.395      0.231

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     20/100      4.18G      1.231      0.833     0.9666         34        640: 100% ━━━━━━━━━━━━ 102/102 8.3it/s 12.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 17/17 6.7it/s 2.5s
                   all        540       3333      0.589      0.346       0.39      0.228

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     21/100      4.18G      1.226     0.8327     0.9519         35        640: 100% ━━━━━━━━━━━━ 102/102 8.5it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 17/17 6.6it/s 2.6s
                   all        540       3333      0.492      0.406      0.403       0.24

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     22/100      4.18G      1.205     0.8169     0.9541         27        640: 100% ━━━━━━━━━━━━ 102/102 8.6it/s 11.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 17/17 5.8it/s 3.0s
                   all        540       3333      0.558      0.393      0.407      0.244

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     23/100      4.18G        1.2     0.8061      0.951         42        640: 100% ━━━━━━━━━━━━ 102/102 8.5it/s 11.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 17/17 5.7it/s 3.0s
                   all        540       3333      0.545      0.405      0.414      0.242

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     24/100      4.18G      1.197     0.8011      0.954         34        640: 100% ━━━━━━━━━━━━ 102/102 8.3it/s 12.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 17/17 7.2it/s 2.4s
                   all        540       3333      0.592      0.386      0.425      0.251

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     25/100      4.18G      1.205     0.8047     0.9434         11        640: 100% ━━━━━━━━━━━━ 102/102 8.4it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 17/17 5.8it/s 2.9s
                   all        540       3333      0.526        0.4      0.413      0.246

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     26/100      4.18G      1.183      0.784     0.9483         49        640: 100% ━━━━━━━━━━━━ 102/102 8.2it/s 12.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 17/17 6.9it/s 2.5s
                   all        540       3333      0.681      0.386      0.442      0.263

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     27/100      4.18G       1.18     0.7777     0.9411         60        640: 100% ━━━━━━━━━━━━ 102/102 8.5it/s 11.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 17/17 5.8it/s 2.9s
                   all        540       3333      0.585      0.413      0.429      0.256

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     28/100      4.18G      1.161     0.7564     0.9315         29        640: 100% ━━━━━━━━━━━━ 102/102 8.4it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 17/17 6.3it/s 2.7s
                   all        540       3333      0.633      0.403      0.448      0.268

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     29/100      4.18G      1.152     0.7541     0.9317         24        640: 100% ━━━━━━━━━━━━ 102/102 8.6it/s 11.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 17/17 7.1it/s 2.4s
                   all        540       3333      0.609      0.423      0.459      0.269

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     30/100      4.18G      1.161     0.7611     0.9346         39        640: 100% ━━━━━━━━━━━━ 102/102 8.2it/s 12.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 17/17 9.1it/s 1.9s
                   all        540       3333      0.532      0.431       0.44      0.265

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     31/100      4.18G      1.133      0.737     0.9325         61        640: 100% ━━━━━━━━━━━━ 102/102 8.0it/s 12.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 17/17 7.0it/s 2.4s
                   all        540       3333      0.545       0.41      0.429      0.249

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     32/100      4.18G      1.136     0.7389     0.9246         18        640: 100% ━━━━━━━━━━━━ 102/102 8.3it/s 12.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 17/17 6.3it/s 2.7s
                   all        540       3333      0.635      0.419      0.459      0.276

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     33/100      4.18G      1.134     0.7373      0.926         17        640: 100% ━━━━━━━━━━━━ 102/102 8.9it/s 11.5s

### **Load best model**

In [ ]:
RUN_DIR = RUNS_ROOT / "acdc_in_domain_yolo11s_seed42"
BEST_MODEL = RUN_DIR / "weights" / "best.pt"

print("Best model exists:", BEST_MODEL.exists())
print("Best model path:", BEST_MODEL)

model = YOLO(str(BEST_MODEL))

Best model exists: True
Best model path: /content/drive/MyDrive/Dissertation/Runs/yolo/acdc_in_domain_yolo11s_seed42/weights/best.pt

### **Global and weather-specific evaluation**

In [ ]:
eval_configs = {
    "global": YOLO_ROOT / "acdc.yaml",
    "fog": YOLO_ROOT / "fog_only.yaml",
    "rain": YOLO_ROOT / "rain_only.yaml",
    "snow": YOLO_ROOT / "snow_only.yaml",
}

results_rows = []

for condition, yaml_path in eval_configs.items():
    print(f"\nEvaluating ACDC {condition.upper()}...")

    metrics = model.val(
        data=str(yaml_path),
        split="test",
        imgsz=640,
        batch=16,
        plots=True,
        project=str(RUN_DIR / "evaluation"),
        name=f"test_{condition}",
        exist_ok=True
    )

    precision = float(metrics.box.mp)
    recall = float(metrics.box.mr)
    map50 = float(metrics.box.map50)
    map75 = float(metrics.box.map75)
    map5095 = float(metrics.box.map)

    f1 = 2 * precision * recall / (precision + recall + 1e-9)

    inference_ms = float(metrics.speed.get("inference", 0))
    fps = 1000 / inference_ms if inference_ms > 0 else None

    results_rows.append({
        "dataset": "ACDC",
        "model": "YOLOv11s",
        "experiment": "in_domain",
        "seed": RANDOM_SEED,
        "condition": condition,
        "mAP50-95": map5095,
        "mAP50": map50,
        "mAP75": map75,
        "Precision": precision,
        "Recall": recall,
        "F1-score": f1,
        "Inference_ms_per_image": inference_ms,
        "FPS": fps
    })

results_df = pd.DataFrame(results_rows)
results_df

Evaluating ACDC GLOBAL...
Ultralytics 8.4.50 🚀 Python-3.12.13 torch-2.10.0+cu128 CUDA:0 (NVIDIA A100-SXM4-40GB, 40441MiB)
val: Fast image access ✅ (ping: 0.6±0.2 ms, read: 204.8±38.1 MB/s, size: 459.2 KB)
val: Scanning /content/drive/.shortcut-targets-by-id/17lufoiYQdFrVMwNFeK91HKX-sBA0zN4V/Dissertation/Datasets/processed/acdc_yolo/labels/test.cache... 540 images, 7 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 540/540 151.0Mit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 34/34 6.2it/s 5.5s
                   all        540       3358      0.765      0.441      0.521      0.333
                person        214        556      0.888      0.336      0.489      0.262
               bicycle         73        117      0.513      0.316      0.313      0.187
                   car        521       2342      0.904      0.632      0.756      0.506
            motorcycle         62         77      0.756      0.273      0.344      0.192
                   bus         44         49      0.726       0.51      0.574      0.393
                 truck        144        217      0.804      0.581      0.652      0.458
Speed: 0.6ms preprocess, 1.0ms inference, 0.0ms loss, 1.4ms postprocess per image
Results saved to /content/drive/.shortcut-targets-by-id/17lufoiYQdFrVMwNFeK91HKX-sBA0zN4V/Dissertation/Runs/yolo/acdc_in_domain_yolo11s_seed42/evaluation/test_global

Evaluating ACDC FOG...
Ultralytics 8.4.50 🚀 Python-3.12.13 torch-2.10.0+cu128 CUDA:0 (NVIDIA A100-SXM4-40GB, 40441MiB)
val: Fast image access ✅ (ping: 0.6±0.2 ms, read: 76.8±114.7 MB/s, size: 400.4 KB)
val: Scanning /content/drive/.shortcut-targets-by-id/17lufoiYQdFrVMwNFeK91HKX-sBA0zN4V/Dissertation/Datasets/processed/acdc_yolo/labels/test_fog... 100 images, 2 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 100/100 7.1it/s 14.0s
val: New cache created: /content/drive/.shortcut-targets-by-id/17lufoiYQdFrVMwNFeK91HKX-sBA0zN4V/Dissertation/Datasets/processed/acdc_yolo/labels/test_fog.cache
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 1.6s/it 11.2s
                   all        100        578      0.858      0.547      0.628      0.413
                person         27         52      0.914      0.346      0.441      0.247
               bicycle         10         13      0.661      0.308      0.323      0.262
                   car         95        408       0.92      0.632       0.76       0.52
            motorcycle          6          7          1      0.534      0.692      0.339
                   bus          6          7      0.764      0.857      0.855      0.612
                 truck         54         91      0.891      0.604      0.695      0.497
Speed: 0.8ms preprocess, 2.1ms inference, 0.0ms loss, 1.0ms postprocess per image
Results saved to /content/drive/.shortcut-targets-by-id/17lufoiYQdFrVMwNFeK91HKX-sBA0zN4V/Dissertation/Runs/yolo/acdc_in_domain_yolo11s_seed42/evaluation/test_fog

Evaluating ACDC RAIN...
Ultralytics 8.4.50 🚀 Python-3.12.13 torch-2.10.0+cu128 CUDA:0 (NVIDIA A100-SXM4-40GB, 40441MiB)
val: Fast image access ✅ (ping: 12.2±26.0 ms, read: 0.5±0.2 MB/s, size: 451.4 KB)
val: Scanning /content/drive/.shortcut-targets-by-id/17lufoiYQdFrVMwNFeK91HKX-sBA0zN4V/Dissertation/Datasets/processed/acdc_yolo/labels/test_rain... 340 images, 4 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 340/340 9.4it/s 36.3s
val: New cache created: /content/drive/.shortcut-targets-by-id/17lufoiYQdFrVMwNFeK91HKX-sBA0zN4V/Dissertation/Datasets/processed/acdc_yolo/labels/test_rain.cache
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 22/22 1.8it/s 12.1s
                   all        340       2082      0.766      0.406      0.484      0.308
                person        129        356      0.897      0.293      0.448       0.23
               bicycle         48         79      0.475      0.253       0.26      0.137
                   car        328       1456      0.906      0.607      0.743      0.489
            motorcycle         51         65      0.845      0.251      0.334      0.192
                   bus         27         31      0.712      0.452       0.48      0.344
                 truck         66         95      0.763      0.579      0.638      0.456
Speed: 0.7ms preprocess, 1.8ms inference, 0.0ms loss, 1.8ms postprocess per image
Results saved to /content/drive/.shortcut-targets-by-id/17lufoiYQdFrVMwNFeK91HKX-sBA0zN4V/Dissertation/Runs/yolo/acdc_in_domain_yolo11s_seed42/evaluation/test_rain

Evaluating ACDC SNOW...
Ultralytics 8.4.50 🚀 Python-3.12.13 torch-2.10.0+cu128 CUDA:0 (NVIDIA A100-SXM4-40GB, 40441MiB)
val: Fast image access ✅ (ping: 1.2±1.3 ms, read: 0.9±0.2 MB/s, size: 543.0 KB)
val: Scanning /content/drive/.shortcut-targets-by-id/17lufoiYQdFrVMwNFeK91HKX-sBA0zN4V/Dissertation/Datasets/processed/acdc_yolo/labels/test_snow... 100 images, 1 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 100/100 7.2it/s 13.9s
val: New cache created: /content/drive/.shortcut-targets-by-id/17lufoiYQdFrVMwNFeK91HKX-sBA0zN4V/Dissertation/Datasets/processed/acdc_yolo/labels/test_snow.cache
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 1.5s/it 10.8s
                   all        100        698      0.724      0.461       0.56      0.356
                person         58        148      0.875      0.426      0.605      0.345
               bicycle         15         25      0.548      0.485      0.466      0.299
                   car         98        478      0.914      0.657      0.797      0.548
            motorcycle          5          5      0.263        0.2      0.175      0.115
                   bus         11         11          1       0.48      0.733      0.458
                 truck         24         31      0.745      0.516      0.583      0.371
Speed: 0.4ms preprocess, 1.1ms inference, 0.0ms loss, 0.8ms postprocess per image
Results saved to /content/drive/.shortcut-targets-by-id/17lufoiYQdFrVMwNFeK91HKX-sBA0zN4V/Dissertation/Runs/yolo/acdc_in_domain_yolo11s_seed42/evaluation/test_snow

,dataset,model,experiment,seed,condition,mAP50-95,mAP50,mAP75,Precision,Recall,F1-score,Inference_ms_per_image,FPS
0,ACDC,YOLOv11s,in_domain,42,global,0.332924,0.521167,0.345546,0.765000,0.441276,0.559700,0.963798,1037.562229
1,ACDC,YOLOv11s,in_domain,42,fog,0.412664,0.627669,0.427248,0.858360,0.546958,0.668158,2.106268,474.773303
2,ACDC,YOLOv11s,in_domain,42,rain,0.308140,0.483562,0.319447,0.766111,0.405806,0.530571,1.796670,556.585328
3,ACDC,YOLOv11s,in_domain,42,snow,0.355982,0.559802,0.364799,0.724260,0.460557,0.563062,1.050349,952.064658

### **Save Results**

In [ ]:
results_csv = RUN_DIR / "acdc_yolo11s_in_domain_results_summary.csv"
results_json = RUN_DIR / "acdc_yolo11s_in_domain_results_summary.json"

results_df.to_csv(results_csv, index=False)

with open(results_json, "w") as f:
    json.dump(results_rows, f, indent=4)

print("Saved:")
print(results_csv)
print(results_json)

Saved:
/content/drive/MyDrive/Dissertation/Runs/yolo/acdc_in_domain_yolo11s_seed42/acdc_yolo11s_in_domain_results_summary.csv
/content/drive/MyDrive/Dissertation/Runs/yolo/acdc_in_domain_yolo11s_seed42/acdc_yolo11s_in_domain_results_summary.json

### **FPS Calcul**

In [ ]:
def get_image_paths_yolo(yolo_root, split_name):
    img_dir = yolo_root / "images" / split_name
    paths = []
    for ext in ["*.jpg", "*.jpeg", "*.png"]:
        paths.extend(img_dir.glob(ext))
    return sorted(paths)

def measure_yolo_fps_loaded_images(model, image_paths, imgsz=640, warmup=30):
    images = []

    for p in image_paths:
        img = cv2.imread(str(p))
        if img is not None:
            images.append(img)

    print("Loaded images:", len(images))

    # Warmup
    for img in images[:warmup]:
        _ = model.predict(
            source=img,
            imgsz=imgsz,
            verbose=False,
            device=0
        )

    if torch.cuda.is_available():
        torch.cuda.synchronize()

    times = []

    for img in images:
        if torch.cuda.is_available():
            torch.cuda.synchronize()

        start = time.perf_counter()

        _ = model.predict(
            source=img,
            imgsz=imgsz,
            verbose=False,
            device=0
        )

        if torch.cuda.is_available():
            torch.cuda.synchronize()

        end = time.perf_counter()
        times.append(end - start)

    avg_ms = np.mean(times) * 1000
    fps = 1000 / avg_ms

    return avg_ms, fps

split_mapping = {
    "global": "test",
    "fog": "test_fog",
    "rain": "test_rain",
    "snow": "test_snow",
}

fps_rows = []

for condition, split_name in split_mapping.items():
    print(f"\nMeasuring YOLO FPS for ACDC {condition.upper()}...")

    image_paths = get_image_paths_yolo(YOLO_ROOT, split_name)

    inference_ms, fps = measure_yolo_fps_loaded_images(
        model=model,
        image_paths=image_paths,
        imgsz=640,
        warmup=30
    )

    fps_rows.append({
        "dataset": "ACDC",
        "model": "YOLOv11s",
        "experiment": "in_domain",
        "seed": 42,
        "condition": condition,
        "Inference_ms_per_image": inference_ms,
        "FPS": fps
    })

fps_df = pd.DataFrame(fps_rows)
fps_df

Measuring YOLO FPS for ACDC GLOBAL...
Loaded images: 540

Measuring YOLO FPS for ACDC FOG...
Loaded images: 100

Measuring YOLO FPS for ACDC RAIN...
Loaded images: 340

Measuring YOLO FPS for ACDC SNOW...
Loaded images: 100

,dataset,model,experiment,seed,condition,Inference_ms_per_image,FPS
0,ACDC,YOLOv11s,in_domain,42,global,11.829795,84.532316
1,ACDC,YOLOv11s,in_domain,42,fog,11.745399,85.139722
2,ACDC,YOLOv11s,in_domain,42,rain,11.654375,85.804685
3,ACDC,YOLOv11s,in_domain,42,snow,11.945242,83.715342

In [ ]:
results_json = RUN_DIR / "acdc_yolo11s_in_domain_results_summary.json"
results_csv = RUN_DIR / "acdc_yolo11s_in_domain_results_summary.csv"

with open(results_json, "r") as f:
    results_data = json.load(f)

results_df = pd.DataFrame(results_data)

for _, fps_row in fps_df.iterrows():
    condition = fps_row["condition"]

    results_df.loc[
        results_df["condition"] == condition,
        "Inference_ms_per_image"
    ] = fps_row["Inference_ms_per_image"]

    results_df.loc[
        results_df["condition"] == condition,
        "FPS"
    ] = fps_row["FPS"]

results_df.to_csv(results_csv, index=False)

with open(results_json, "w") as f:
    json.dump(results_df.to_dict(orient="records"), f, indent=4)

results_df

,dataset,model,experiment,seed,condition,mAP50-95,mAP50,mAP75,Precision,Recall,F1-score,Inference_ms_per_image,FPS
0,ACDC,YOLOv11s,in_domain,42,global,0.332924,0.521167,0.345546,0.765000,0.441276,0.559700,11.829795,84.532316
1,ACDC,YOLOv11s,in_domain,42,fog,0.412664,0.627669,0.427248,0.858360,0.546958,0.668158,11.745399,85.139722
2,ACDC,YOLOv11s,in_domain,42,rain,0.308140,0.483562,0.319447,0.766111,0.405806,0.530571,11.654375,85.804685
3,ACDC,YOLOv11s,in_domain,42,snow,0.355982,0.559802,0.364799,0.724260,0.460557,0.563062,11.945242,83.715342