# **ACDC In-Domain Training — Faster R-CNN - seed 456**

The notebook includes:
*   Configuration of the Faster R-CNN R50-FPN architecture with COCO pretrained weights
*   Model training and validation on the ACDC dataset
*   Global evaluation on the ACDC test set and weather-specific evaluation on fog, rain, and snow subsets

### **Mount drive**

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

## **Install Detectron**

In [2]:
# Fix numpy compatibility
!pip install -q --force-reinstall numpy==1.26.4

# Build dependencies
!pip install -q setuptools==68.0.0 wheel cython

#Import detectron from the source
%cd /content

import os

if not os.path.exists("/content/detectron2"):
    !git clone https://github.com/facebookresearch/detectron2.git

%cd /content/detectron2
!python -m pip install --no-build-isolation -e .
%cd /content

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
rasterio 1.5.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
tobler 0.14.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
cupy-cuda12x 14.0.1 requires numpy<2.6,>=2.0, but you have numpy 1.26.4 which is incompatible.
opencv-python-headless 5.0.0.93 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
tifffile 2026.4.11 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
pytensor 2.38.3 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
shap 0.52.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
opencv-contrib-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
xarray-einstats 0.10.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
jaxlib 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
jax 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
opencv-python 5.0.0.93 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
/content
/content/detectron2
Obtaining file:///content/detectron2
  Preparing metadata (setup.py) ... done
Requirement already satisfied: Pillow>=7.1 in /usr/local/lib/python3.12/dist-packages (from detectron2==0.6) (11.3.0)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from detectron2==0.6) (3.10.0)
Requirement already satisfied: pycocotools>=2.0.2 in /usr/local/lib/python3.12/dist-packages (from detectron2==0.6) (2.0.11)
Requirement already satisfied: termcolor>=1.1 in /usr/local/lib/python3.12/dist-packages (from detectron2==0.6) (3.3.0)
Requirement already satisfied: yacs>=0.1.8 in /usr/local/lib/python3.12/dist-packages (from detectron2==0.6) (0.1.8)
Requirement already satisfied: tabulate in /usr/local/lib/python3.12/dist-packages (from detectron2==0.6) (0.9.0)
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.12/dist-packages (from detectron2==0.6) (3.1.2)
Requirement already satisfied: tqdm>4.29.0 in /usr/local/lib/python3.12/dist-packages (from detectron2==0.6) (4.67.3)
Requirement already satisfied: tensorboard in /usr/local/lib/python3.12/dist-packages (from detectron2==0.6) (2.20.0)
Requirement already satisfied: fvcore<0.1.6,>=0.1.5 in /usr/local/lib/python3.12/dist-packages (from detectron2==0.6) (0.1.5.post20221221)
Requirement already satisfied: iopath<0.1.10,>=0.1.7 in /usr/local/lib/python3.12/dist-packages (from detectron2==0.6) (0.1.9)
Requirement already satisfied: omegaconf<2.4,>=2.1 in /usr/local/lib/python3.12/dist-packages (from detectron2==0.6) (2.3.1)
Requirement already satisfied: hydra-core>=1.1 in /usr/local/lib/python3.12/dist-packages (from detectron2==0.6) (1.3.4)
Requirement already satisfied: black in /usr/local/lib/python3.12/dist-packages (from detectron2==0.6) (26.5.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from detectron2==0.6) (26.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from fvcore<0.1.6,>=0.1.5->detectron2==0.6) (1.26.4)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from fvcore<0.1.6,>=0.1.5->detectron2==0.6) (6.0.3)
Requirement already satisfied: antlr4-python3-runtime==4.9.* in /usr/local/lib/python3.12/dist-packages (from hydra-core>=1.1->detectron2==0.6) (4.9.3)
Requirement already satisfied: portalocker in /usr/local/lib/python3.12/dist-packages (from iopath<0.1.10,>=0.1.7->detectron2==0.6) (3.2.0)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.12/dist-packages (from black->detectron2==0.6) (8.4.2)
Requirement already satisfied: mypy-extensions>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from black->detectron2==0.6) (1.1.0)
Requirement already satisfied: pathspec>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from black->detectron2==0.6) (1.1.1)
Requirement already satisfied: platformdirs>=2 in /usr/local/lib/python3.12/dist-packages (from black->detectron2==0.6) (4.10.0)
Requirement already satisfied: pytokens~=0.4.0 in /usr/local/lib/python3.12/dist-packages (from black->detectron2==0.6) (0.4.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->detectron2==0.6) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->detectron2==0.6) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->detectron2==0.6) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->detectron2==0.6) (1.5.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->detectron2==0.6) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib->detectron2==0.6) (2.9.0.post0)
Requirement already satisfied: absl-py>=0.4 in /usr/local/lib/python3.12/dist-packages (from tensorboard->detectron2==0.6) (1.4.0)
Requirement already satisfied: grpcio>=1.48.2 in /usr/local/lib/python3.12/dist-packages (from tensorboard->detectron2==0.6) (1.82.1)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.12/dist-packages (from tensorboard->detectron2==0.6) (3.10.2)
Requirement already satisfied: protobuf!=4.24.0,>=3.19.6 in /usr/local/lib/python3.12/dist-packages (from tensorboard->detectron2==0.6) (5.29.6)
Requirement already satisfied: setuptools>=41.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorboard->detectron2==0.6) (68.0.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from tensorboard->detectron2==0.6) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from tensorboard->detectron2==0.6) (3.1.8)
Requirement already satisfied: typing-extensions~=4.12 in /usr/local/lib/python3.12/dist-packages (from grpcio>=1.48.2->tensorboard->detectron2==0.6) (4.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib->detectron2==0.6) (1.17.0)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from werkzeug>=1.0.1->tensorboard->detectron2==0.6) (3.0.3)
Installing collected packages: detectron2
  Attempting uninstall: detectron2
    Found existing installation: detectron2 0.6
    Uninstalling detectron2-0.6:
      Successfully uninstalled detectron2-0.6
  Running setup.py develop for detectron2
Successfully installed detectron2-0.6
/content

In [ ]:
import os
os.kill(os.getpid(), 9)

In [3]:
import numpy as np
print(np.__version__)

1.26.4

### **Import librairies**

In [4]:
from pathlib import Path
import os
import json
import time
import cv2
import torch
import pandas as pd
import numpy as np

from detectron2.data import DatasetCatalog, MetadataCatalog
from detectron2.data.datasets import register_pascal_voc
from detectron2.config import get_cfg
from detectron2 import model_zoo
from detectron2.engine import DefaultTrainer, DefaultPredictor
from detectron2.evaluation import COCOEvaluator, inference_on_dataset
from detectron2.data import build_detection_test_loader
from detectron2.checkpoint import DetectionCheckpointer
from detectron2.engine import hooks

### **Path configuration & check GPU**

In [5]:
PROJECT_ROOT = Path("/content/drive/MyDrive/Dissertation")

ACDC_VOC_ROOT = PROJECT_ROOT / "Datasets/processed/acdc_voc"
RUNS_ROOT = PROJECT_ROOT / "Runs/faster_rcnn"
OUTPUT_DIR = RUNS_ROOT / "acdc_in_domain_faster_rcnn_seed456"

CLASS_NAMES = [
    "person",
    "bicycle",
    "car",
    "motorcycle",
    "bus",
    "truck"
]

RANDOM_SEED = 456

print("ACDC VOC exists:", ACDC_VOC_ROOT.exists())
print("Train split exists:", (ACDC_VOC_ROOT / "ImageSets/Main/train.txt").exists())
print("CUDA available:", torch.cuda.is_available())
print("GPU:", torch.cuda.get_device_name(0) if torch.cuda.is_available() else "CPU")

ACDC VOC exists: True
Train split exists: True
CUDA available: True
GPU: NVIDIA A100-SXM4-40GB

### **Register ACDC VOC datasets**

In [6]:
CLASS_NAMES = ["person", "bicycle", "car", "motorcycle", "bus", "truck"]

datasets = {
    "acdc_train": "train",
    "acdc_val": "val",
    "acdc_test": "test",
    "acdc_test_fog": "test_fog",
    "acdc_test_rain": "test_rain",
    "acdc_test_snow": "test_snow",
}

def reset_detectron2_dataset(name):
    if name in DatasetCatalog.list():
        DatasetCatalog.remove(name)

    if name in MetadataCatalog.list():
        MetadataCatalog.remove(name)

for dataset_name in datasets:
    reset_detectron2_dataset(dataset_name)

for dataset_name, split_name in datasets.items():
    register_pascal_voc(
        name=dataset_name,
        dirname=str(ACDC_VOC_ROOT),
        split=split_name,
        year="",
        class_names=CLASS_NAMES
    )

print("ACDC datasets registered with custom classes.")

ACDC datasets registered with custom classes.

In [7]:
for dataset_name in datasets:
    print(dataset_name, MetadataCatalog.get(dataset_name).thing_classes)

acdc_train ['person', 'bicycle', 'car', 'motorcycle', 'bus', 'truck']
acdc_val ['person', 'bicycle', 'car', 'motorcycle', 'bus', 'truck']
acdc_test ['person', 'bicycle', 'car', 'motorcycle', 'bus', 'truck']
acdc_test_fog ['person', 'bicycle', 'car', 'motorcycle', 'bus', 'truck']
acdc_test_rain ['person', 'bicycle', 'car', 'motorcycle', 'bus', 'truck']
acdc_test_snow ['person', 'bicycle', 'car', 'motorcycle', 'bus', 'truck']

### **Mini validation**

In [8]:
for dataset_name in datasets.keys():
    dataset_dicts = DatasetCatalog.get(dataset_name)
    metadata = MetadataCatalog.get(dataset_name)

    print(f"{dataset_name}: {len(dataset_dicts)} images")
    print("classes:", metadata.thing_classes)

acdc_train: 1620 images
classes: ['person', 'bicycle', 'car', 'motorcycle', 'bus', 'truck']
acdc_val: 540 images
classes: ['person', 'bicycle', 'car', 'motorcycle', 'bus', 'truck']
acdc_test: 540 images
classes: ['person', 'bicycle', 'car', 'motorcycle', 'bus', 'truck']
acdc_test_fog: 100 images
classes: ['person', 'bicycle', 'car', 'motorcycle', 'bus', 'truck']
acdc_test_rain: 340 images
classes: ['person', 'bicycle', 'car', 'motorcycle', 'bus', 'truck']
acdc_test_snow: 100 images
classes: ['person', 'bicycle', 'car', 'motorcycle', 'bus', 'truck']

### **Checkpoints configuration**

In [9]:
IMS_PER_BATCH = 4
EPOCHS = 100

NUM_TRAIN_IMAGES = len(DatasetCatalog.get("acdc_train"))
STEPS_PER_EPOCH = int(np.ceil(NUM_TRAIN_IMAGES / IMS_PER_BATCH))
MAX_ITER = STEPS_PER_EPOCH * EPOCHS

CHECKPOINT_PERIOD = 5000
EVAL_PERIOD = STEPS_PER_EPOCH * 5   # validation toutes les 5 epochs

print("Train images:", NUM_TRAIN_IMAGES)
print("Steps per epoch:", STEPS_PER_EPOCH)
print("MAX_ITER:", MAX_ITER)
print("Checkpoint period:", CHECKPOINT_PERIOD)
print("Eval period:", EVAL_PERIOD)

Train images: 1620
Steps per epoch: 405
MAX_ITER: 40500
Checkpoint period: 5000
Eval period: 2025

### **trainer with best checkpoint**

In [10]:
class TrainerWithBestCheckpoint(DefaultTrainer):
    @classmethod
    def build_evaluator(cls, cfg, dataset_name, output_folder=None):
        if output_folder is None:
            output_folder = os.path.join(cfg.OUTPUT_DIR, "eval", dataset_name)
        return COCOEvaluator(dataset_name, cfg, False, output_folder)

    def build_hooks(self):
        hook_list = super().build_hooks()

        hook_list.insert(
            -1,
            hooks.BestCheckpointer(
                self.cfg.TEST.EVAL_PERIOD,
                DetectionCheckpointer(self.model, self.cfg.OUTPUT_DIR),
                "bbox/AP",
                mode="max",
                file_prefix="model_best"
            )
        )

        return hook_list

### **Config**

In [11]:
cfg = get_cfg()

cfg.merge_from_file(
    model_zoo.get_config_file("COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml")
)

cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url(
    "COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml"
)

cfg.DATASETS.TRAIN = ("acdc_train",)
cfg.DATASETS.TEST = ("acdc_val",)

cfg.DATALOADER.NUM_WORKERS = 2

cfg.SOLVER.IMS_PER_BATCH = IMS_PER_BATCH
cfg.SOLVER.BASE_LR = 0.00025
cfg.SOLVER.MAX_ITER = MAX_ITER
cfg.SOLVER.STEPS = []
cfg.SOLVER.CHECKPOINT_PERIOD = CHECKPOINT_PERIOD

cfg.TEST.EVAL_PERIOD = EVAL_PERIOD

cfg.MODEL.ROI_HEADS.NUM_CLASSES = len(CLASS_NAMES)
cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.5

cfg.SEED = RANDOM_SEED
cfg.OUTPUT_DIR = str(OUTPUT_DIR)

os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)

with open(OUTPUT_DIR / "config.yaml", "w") as f:
    f.write(cfg.dump())

print("Config ready.")
print("Output:", cfg.OUTPUT_DIR)

Config ready.
Output: /content/drive/MyDrive/Dissertation/Runs/faster_rcnn/acdc_in_domain_faster_rcnn_seed456

### **Train**

In [12]:
trainer = TrainerWithBestCheckpoint(cfg)
trainer.resume_or_load(resume=True)
trainer.train()

[07/16 17:34:11 d2.engine.defaults]: Model:
GeneralizedRCNN(
  (backbone): FPN(
    (fpn_lateral2): Conv2d(256, 256, kernel_size=(1, 1), stride=(1, 1))
    (fpn_output2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (fpn_lateral3): Conv2d(512, 256, kernel_size=(1, 1), stride=(1, 1))
    (fpn_output3): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (fpn_lateral4): Conv2d(1024, 256, kernel_size=(1, 1), stride=(1, 1))
    (fpn_output4): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (fpn_lateral5): Conv2d(2048, 256, kernel_size=(1, 1), stride=(1, 1))
    (fpn_output5): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (top_block): LastLevelMaxPool()
    (bottom_up): ResNet(
      (stem): BasicStem(
        (conv1): Conv2d(
          3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False
          (norm): FrozenBatchNorm2d(num_features=64, eps=1e-05)
        )
      )
      (res2): Sequential(
        (0): BottleneckBlock(
          (shortcut): Conv2d(
            64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
          (conv1): Conv2d(
            64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=64, eps=1e-05)
          )
          (conv2): Conv2d(
            64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=64, eps=1e-05)
          )
          (conv3): Conv2d(
            64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
        )
        (1): BottleneckBlock(
          (conv1): Conv2d(
            256, 64, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=64, eps=1e-05)
          )
          (conv2): Conv2d(
            64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=64, eps=1e-05)
          )
          (conv3): Conv2d(
            64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
        )
        (2): BottleneckBlock(
          (conv1): Conv2d(
            256, 64, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=64, eps=1e-05)
          )
          (conv2): Conv2d(
            64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=64, eps=1e-05)
          )
          (conv3): Conv2d(
            64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
        )
      )
      (res3): Sequential(
        (0): BottleneckBlock(
          (shortcut): Conv2d(
            256, 512, kernel_size=(1, 1), stride=(2, 2), bias=False
            (norm): FrozenBatchNorm2d(num_features=512, eps=1e-05)
          )
          (conv1): Conv2d(
            256, 128, kernel_size=(1, 1), stride=(2, 2), bias=False
            (norm): FrozenBatchNorm2d(num_features=128, eps=1e-05)
          )
          (conv2): Conv2d(
            128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=128, eps=1e-05)
          )
          (conv3): Conv2d(
            128, 512, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=512, eps=1e-05)
          )
        )
        (1): BottleneckBlock(
          (conv1): Conv2d(
            512, 128, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=128, eps=1e-05)
          )
          (conv2): Conv2d(
            128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=128, eps=1e-05)
          )
          (conv3): Conv2d(
            128, 512, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=512, eps=1e-05)
          )
        )
        (2): BottleneckBlock(
          (conv1): Conv2d(
            512, 128, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=128, eps=1e-05)
          )
          (conv2): Conv2d(
            128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=128, eps=1e-05)
          )
          (conv3): Conv2d(
            128, 512, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=512, eps=1e-05)
          )
        )
        (3): BottleneckBlock(
          (conv1): Conv2d(
            512, 128, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=128, eps=1e-05)
          )
          (conv2): Conv2d(
            128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=128, eps=1e-05)
          )
          (conv3): Conv2d(
            128, 512, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=512, eps=1e-05)
          )
        )
      )
      (res4): Sequential(
        (0): BottleneckBlock(
          (shortcut): Conv2d(
            512, 1024, kernel_size=(1, 1), stride=(2, 2), bias=False
            (norm): FrozenBatchNorm2d(num_features=1024, eps=1e-05)
          )
          (conv1): Conv2d(
            512, 256, kernel_size=(1, 1), stride=(2, 2), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
          (conv2): Conv2d(
            256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
          (conv3): Conv2d(
            256, 1024, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=1024, eps=1e-05)
          )
        )
        (1): BottleneckBlock(
          (conv1): Conv2d(
            1024, 256, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
          (conv2): Conv2d(
            256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
          (conv3): Conv2d(
            256, 1024, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=1024, eps=1e-05)
          )
        )
        (2): BottleneckBlock(
          (conv1): Conv2d(
            1024, 256, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
          (conv2): Conv2d(
            256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
          (conv3): Conv2d(
            256, 1024, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=1024, eps=1e-05)
          )
        )
        (3): BottleneckBlock(
          (conv1): Conv2d(
            1024, 256, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
          (conv2): Conv2d(
            256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
          (conv3): Conv2d(
            256, 1024, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=1024, eps=1e-05)
          )
        )
        (4): BottleneckBlock(
          (conv1): Conv2d(
            1024, 256, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
          (conv2): Conv2d(
            256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
          (conv3): Conv2d(
            256, 1024, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=1024, eps=1e-05)
          )
        )
        (5): BottleneckBlock(
          (conv1): Conv2d(
            1024, 256, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
          (conv2): Conv2d(
            256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
          (conv3): Conv2d(
            256, 1024, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=1024, eps=1e-05)
          )
        )
      )
      (res5): Sequential(
        (0): BottleneckBlock(
          (shortcut): Conv2d(
            1024, 2048, kernel_size=(1, 1), stride=(2, 2), bias=False
            (norm): FrozenBatchNorm2d(num_features=2048, eps=1e-05)
          )
          (conv1): Conv2d(
            1024, 512, kernel_size=(1, 1), stride=(2, 2), bias=False
            (norm): FrozenBatchNorm2d(num_features=512, eps=1e-05)
          )
          (conv2): Conv2d(
            512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=512, eps=1e-05)
          )
          (conv3): Conv2d(
            512, 2048, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=2048, eps=1e-05)
          )
        )
        (1): BottleneckBlock(
          (conv1): Conv2d(
            2048, 512, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=512, eps=1e-05)
          )
          (conv2): Conv2d(
            512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=512, eps=1e-05)
          )
          (conv3): Conv2d(
            512, 2048, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=2048, eps=1e-05)
          )
        )
        (2): BottleneckBlock(
          (conv1): Conv2d(
            2048, 512, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=512, eps=1e-05)
          )
          (conv2): Conv2d(
            512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=512, eps=1e-05)
          )
          (conv3): Conv2d(
            512, 2048, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=2048, eps=1e-05)
          )
        )
      )
    )
  )
  (proposal_generator): RPN(
    (rpn_head): StandardRPNHead(
      (conv): Conv2d(
        256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1)
        (activation): ReLU()
      )
      (objectness_logits): Conv2d(256, 3, kernel_size=(1, 1), stride=(1, 1))
      (anchor_deltas): Conv2d(256, 12, kernel_size=(1, 1), stride=(1, 1))
    )
    (anchor_generator): DefaultAnchorGenerator(
      (cell_anchors): BufferList()
    )
  )
  (roi_heads): StandardROIHeads(
    (box_pooler): ROIPooler(
      (level_poolers): ModuleList(
        (0): ROIAlign(output_size=(7, 7), spatial_scale=0.25, sampling_ratio=0, aligned=True)
        (1): ROIAlign(output_size=(7, 7), spatial_scale=0.125, sampling_ratio=0, aligned=True)
        (2): ROIAlign(output_size=(7, 7), spatial_scale=0.0625, sampling_ratio=0, aligned=True)
        (3): ROIAlign(output_size=(7, 7), spatial_scale=0.03125, sampling_ratio=0, aligned=True)
      )
    )
    (box_head): FastRCNNConvFCHead(
      (flatten): Flatten(start_dim=1, end_dim=-1)
      (fc1): Linear(in_features=12544, out_features=1024, bias=True)
      (fc_relu1): ReLU()
      (fc2): Linear(in_features=1024, out_features=1024, bias=True)
      (fc_relu2): ReLU()
    )
    (box_predictor): FastRCNNOutputLayers(
      (cls_score): Linear(in_features=1024, out_features=7, bias=True)
      (bbox_pred): Linear(in_features=1024, out_features=24, bias=True)
    )
  )
)
[07/16 17:34:14 d2.data.build]: Removed 29 images with no usable annotations. 1591 images left.
[07/16 17:34:14 d2.data.build]: Distribution of instances among all 6 categories:
|  category  | #instances   |  category  | #instances   |  category  | #instances   |
|:----------:|:-------------|:----------:|:-------------|:----------:|:-------------|
|   person   | 1731         |  bicycle   | 337          |    car     | 7071         |
| motorcycle | 182          |    bus     | 190          |   truck    | 664          |
|            |              |            |              |            |              |
|   total    | 10175        |            |              |            |              |
[07/16 17:34:14 d2.data.dataset_mapper]: [DatasetMapper] Augmentations used in training: [ResizeShortestEdge(short_edge_length=(640, 672, 704, 736, 768, 800), max_size=1333, sample_style='choice'), RandomFlip()]
[07/16 17:34:14 d2.data.build]: Using training sampler TrainingSampler
[07/16 17:34:14 d2.data.common]: Serializing the dataset using: <class 'detectron2.data.common._TorchSerializedList'>
[07/16 17:34:14 d2.data.common]: Serializing 1591 elements to byte tensors and concatenating them all ...
[07/16 17:34:14 d2.data.common]: Serialized dataset takes 1.21 MiB
[07/16 17:34:14 d2.data.build]: Making batched data loader with batch_size=4
[07/16 17:34:14 d2.checkpoint.detection_checkpoint]: [DetectionCheckpointer] Loading from https://dl.fbaipublicfiles.com/detectron2/COCO-Detection/faster_rcnn_R_50_FPN_3x/137849458/model_final_280758.pkl ...

model_final_280758.pkl: 167MB [00:01, 138MB/s]
WARNING:fvcore.common.checkpoint:Skip loading parameter 'roi_heads.box_predictor.cls_score.weight' to the model due to incompatible shapes: (81, 1024) in the checkpoint but (7, 1024) in the model! You might want to double check if this is expected.
WARNING:fvcore.common.checkpoint:Skip loading parameter 'roi_heads.box_predictor.cls_score.bias' to the model due to incompatible shapes: (81,) in the checkpoint but (7,) in the model! You might want to double check if this is expected.
WARNING:fvcore.common.checkpoint:Skip loading parameter 'roi_heads.box_predictor.bbox_pred.weight' to the model due to incompatible shapes: (320, 1024) in the checkpoint but (24, 1024) in the model! You might want to double check if this is expected.
WARNING:fvcore.common.checkpoint:Skip loading parameter 'roi_heads.box_predictor.bbox_pred.bias' to the model due to incompatible shapes: (320,) in the checkpoint but (24,) in the model! You might want to double check if this is expected.
WARNING:fvcore.common.checkpoint:Some model parameters or buffers are not found in the checkpoint:
roi_heads.box_predictor.bbox_pred.{bias, weight}
roi_heads.box_predictor.cls_score.{bias, weight}

[07/16 17:34:15 d2.engine.train_loop]: Starting training from iteration 0

/usr/local/lib/python3.12/dist-packages/torch/functional.py:505: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:4381.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
W0716 17:34:19.157000 7000 torch/fx/_symbolic_trace.py:53] is_fx_tracing will return true for both fx.symbolic_trace and torch.export. Please use is_fx_tracing_symbolic_tracing() for specifically fx.symbolic_trace or torch.compiler.is_compiling() for specifically torch.export/compile.

[07/16 17:34:37 d2.utils.events]:  eta: 9:24:18  iter: 19  total_loss: 2.758  loss_cls: 2.175  loss_box_reg: 0.5021  loss_rpn_cls: 0.03126  loss_rpn_loc: 0.09134    time: 0.9931  last_time: 0.6863  data_time: 0.7832  last_data_time: 0.5220   lr: 4.9953e-06  max_mem: 4082M
[07/16 17:34:57 d2.utils.events]:  eta: 9:05:06  iter: 39  total_loss: 2.645  loss_cls: 2.038  loss_box_reg: 0.4302  loss_rpn_cls: 0.03556  loss_rpn_loc: 0.07867    time: 0.8900  last_time: 0.8213  data_time: 0.6360  last_data_time: 0.6611   lr: 9.9902e-06  max_mem: 4082M
[07/16 17:35:14 d2.utils.events]:  eta: 9:15:48  iter: 59  total_loss: 2.459  loss_cls: 1.782  loss_box_reg: 0.46  loss_rpn_cls: 0.04378  loss_rpn_loc: 0.09842    time: 0.8690  last_time: 0.6703  data_time: 0.6687  last_data_time: 0.5219   lr: 1.4985e-05  max_mem: 4082M
[07/16 17:35:30 d2.utils.events]:  eta: 9:08:55  iter: 79  total_loss: 2.008  loss_cls: 1.425  loss_box_reg: 0.4138  loss_rpn_cls: 0.04395  loss_rpn_loc: 0.1289    time: 0.8590  last_time: 0.6642  data_time: 0.6679  last_data_time: 0.4868   lr: 1.998e-05  max_mem: 4082M
[07/16 17:35:46 d2.utils.events]:  eta: 9:07:58  iter: 99  total_loss: 1.641  loss_cls: 1.018  loss_box_reg: 0.43  loss_rpn_cls: 0.03685  loss_rpn_loc: 0.1241    time: 0.8457  last_time: 0.6535  data_time: 0.6321  last_data_time: 0.4959   lr: 2.4975e-05  max_mem: 4082M
[07/16 17:36:02 d2.utils.events]:  eta: 8:58:45  iter: 119  total_loss: 1.396  loss_cls: 0.7057  loss_box_reg: 0.4469  loss_rpn_cls: 0.03799  loss_rpn_loc: 0.1365    time: 0.8373  last_time: 0.7928  data_time: 0.6374  last_data_time: 0.6324   lr: 2.997e-05  max_mem: 4082M
[07/16 17:36:19 d2.utils.events]:  eta: 8:54:47  iter: 139  total_loss: 1.081  loss_cls: 0.5127  loss_box_reg: 0.4098  loss_rpn_cls: 0.03568  loss_rpn_loc: 0.1173    time: 0.8351  last_time: 0.7085  data_time: 0.6612  last_data_time: 0.5287   lr: 3.4965e-05  max_mem: 4082M
[07/16 17:36:35 d2.utils.events]:  eta: 8:53:40  iter: 159  total_loss: 1.017  loss_cls: 0.4395  loss_box_reg: 0.3795  loss_rpn_cls: 0.03617  loss_rpn_loc: 0.09345    time: 0.8327  last_time: 0.6586  data_time: 0.6563  last_data_time: 0.4999   lr: 3.996e-05  max_mem: 4082M
[07/16 17:36:51 d2.utils.events]:  eta: 8:52:50  iter: 179  total_loss: 1.054  loss_cls: 0.4676  loss_box_reg: 0.4286  loss_rpn_cls: 0.0343  loss_rpn_loc: 0.08265    time: 0.8272  last_time: 0.6936  data_time: 0.6199  last_data_time: 0.5331   lr: 4.4955e-05  max_mem: 4082M
[07/16 17:37:06 d2.utils.events]:  eta: 8:48:19  iter: 199  total_loss: 1.039  loss_cls: 0.4403  loss_box_reg: 0.471  loss_rpn_cls: 0.03153  loss_rpn_loc: 0.07355    time: 0.8214  last_time: 0.7284  data_time: 0.6103  last_data_time: 0.5685   lr: 4.995e-05  max_mem: 4082M
[07/16 17:37:22 d2.utils.events]:  eta: 8:48:04  iter: 219  total_loss: 1.051  loss_cls: 0.4281  loss_box_reg: 0.4364  loss_rpn_cls: 0.03207  loss_rpn_loc: 0.1116    time: 0.8188  last_time: 0.8583  data_time: 0.6304  last_data_time: 0.6983   lr: 5.4945e-05  max_mem: 4082M
[07/16 17:37:39 d2.utils.events]:  eta: 8:50:57  iter: 239  total_loss: 0.9025  loss_cls: 0.3653  loss_box_reg: 0.4095  loss_rpn_cls: 0.03031  loss_rpn_loc: 0.09974    time: 0.8203  last_time: 0.7132  data_time: 0.6754  last_data_time: 0.5538   lr: 5.994e-05  max_mem: 4082M
[07/16 17:37:55 d2.utils.events]:  eta: 8:47:32  iter: 259  total_loss: 0.9566  loss_cls: 0.354  loss_box_reg: 0.4527  loss_rpn_cls: 0.03161  loss_rpn_loc: 0.0972    time: 0.8193  last_time: 0.7105  data_time: 0.6471  last_data_time: 0.5508   lr: 6.4935e-05  max_mem: 4082M
[07/16 17:38:11 d2.utils.events]:  eta: 8:50:02  iter: 279  total_loss: 0.98  loss_cls: 0.3578  loss_box_reg: 0.469  loss_rpn_cls: 0.0293  loss_rpn_loc: 0.09183    time: 0.8190  last_time: 0.8490  data_time: 0.6552  last_data_time: 0.6889   lr: 6.993e-05  max_mem: 4082M
[07/16 17:38:27 d2.utils.events]:  eta: 8:49:58  iter: 299  total_loss: 0.9229  loss_cls: 0.3286  loss_box_reg: 0.4238  loss_rpn_cls: 0.03371  loss_rpn_loc: 0.1229    time: 0.8175  last_time: 0.9408  data_time: 0.6377  last_data_time: 0.7791   lr: 7.4925e-05  max_mem: 4082M
[07/16 17:38:44 d2.utils.events]:  eta: 8:50:32  iter: 319  total_loss: 1.011  loss_cls: 0.3327  loss_box_reg: 0.4308  loss_rpn_cls: 0.02667  loss_rpn_loc: 0.09745    time: 0.8182  last_time: 0.7815  data_time: 0.6654  last_data_time: 0.6228   lr: 7.992e-05  max_mem: 4082M
[07/16 17:39:01 d2.utils.events]:  eta: 8:50:40  iter: 339  total_loss: 0.9123  loss_cls: 0.2791  loss_box_reg: 0.4287  loss_rpn_cls: 0.03593  loss_rpn_loc: 0.1058    time: 0.8197  last_time: 0.7467  data_time: 0.6826  last_data_time: 0.5698   lr: 8.4915e-05  max_mem: 4082M
[07/16 17:39:16 d2.utils.events]:  eta: 8:48:32  iter: 359  total_loss: 0.8254  loss_cls: 0.2738  loss_box_reg: 0.4261  loss_rpn_cls: 0.03579  loss_rpn_loc: 0.09664    time: 0.8167  last_time: 0.7984  data_time: 0.6022  last_data_time: 0.6369   lr: 8.991e-05  max_mem: 4082M
[07/16 17:39:30 d2.utils.events]:  eta: 8:43:12  iter: 379  total_loss: 0.8139  loss_cls: 0.2822  loss_box_reg: 0.419  loss_rpn_cls: 0.02989  loss_rpn_loc: 0.06716    time: 0.8122  last_time: 0.6697  data_time: 0.5732  last_data_time: 0.5107   lr: 9.4905e-05  max_mem: 4082M
[07/16 17:39:45 d2.utils.events]:  eta: 8:41:28  iter: 399  total_loss: 0.9105  loss_cls: 0.2983  loss_box_reg: 0.4811  loss_rpn_cls: 0.02972  loss_rpn_loc: 0.1035    time: 0.8078  last_time: 0.1872  data_time: 0.5646  last_data_time: 0.0261   lr: 9.99e-05  max_mem: 4082M
[07/16 17:39:49 d2.utils.events]:  eta: 8:33:53  iter: 419  total_loss: 0.8465  loss_cls: 0.3003  loss_box_reg: 0.4462  loss_rpn_cls: 0.02908  loss_rpn_loc: 0.09349    time: 0.7784  last_time: 0.2076  data_time: 0.0317  last_data_time: 0.0447   lr: 0.0001049  max_mem: 4082M
[07/16 17:39:53 d2.utils.events]:  eta: 8:30:50  iter: 439  total_loss: 0.8057  loss_cls: 0.2804  loss_box_reg: 0.39  loss_rpn_cls: 0.02745  loss_rpn_loc: 0.1003    time: 0.7516  last_time: 0.1897  data_time: 0.0315  last_data_time: 0.0276   lr: 0.00010989  max_mem: 4082M
[07/16 17:39:57 d2.utils.events]:  eta: 8:22:40  iter: 459  total_loss: 0.8198  loss_cls: 0.2648  loss_box_reg: 0.4183  loss_rpn_cls: 0.03484  loss_rpn_loc: 0.08549    time: 0.7274  last_time: 0.1866  data_time: 0.0357  last_data_time: 0.0237   lr: 0.00011489  max_mem: 4082M
[07/16 17:40:00 d2.utils.events]:  eta: 8:15:37  iter: 479  total_loss: 0.9337  loss_cls: 0.2973  loss_box_reg: 0.4033  loss_rpn_cls: 0.02542  loss_rpn_loc: 0.09717    time: 0.7050  last_time: 0.1889  data_time: 0.0307  last_data_time: 0.0274   lr: 0.00011988  max_mem: 4082M
[07/16 17:40:04 d2.utils.events]:  eta: 8:08:05  iter: 499  total_loss: 0.7824  loss_cls: 0.2354  loss_box_reg: 0.3692  loss_rpn_cls: 0.02776  loss_rpn_loc: 0.1064    time: 0.6844  last_time: 0.1883  data_time: 0.0298  last_data_time: 0.0264   lr: 0.00012488  max_mem: 4082M
[07/16 17:40:08 d2.utils.events]:  eta: 7:58:29  iter: 519  total_loss: 0.7447  loss_cls: 0.2328  loss_box_reg: 0.3572  loss_rpn_cls: 0.03243  loss_rpn_loc: 0.06486    time: 0.6655  last_time: 0.1959  data_time: 0.0341  last_data_time: 0.0307   lr: 0.00012987  max_mem: 4083M
[07/16 17:40:12 d2.utils.events]:  eta: 7:51:39  iter: 539  total_loss: 0.7172  loss_cls: 0.2433  loss_box_reg: 0.3298  loss_rpn_cls: 0.03324  loss_rpn_loc: 0.09459    time: 0.6480  last_time: 0.2090  data_time: 0.0343  last_data_time: 0.0487   lr: 0.00013487  max_mem: 4083M
[07/16 17:40:16 d2.utils.events]:  eta: 7:46:45  iter: 559  total_loss: 0.6848  loss_cls: 0.2274  loss_box_reg: 0.3216  loss_rpn_cls: 0.02973  loss_rpn_loc: 0.08343    time: 0.6318  last_time: 0.1999  data_time: 0.0344  last_data_time: 0.0365   lr: 0.00013986  max_mem: 4083M
[07/16 17:40:20 d2.utils.events]:  eta: 7:42:19  iter: 579  total_loss: 0.6597  loss_cls: 0.221  loss_box_reg: 0.2702  loss_rpn_cls: 0.02559  loss_rpn_loc: 0.1177    time: 0.6166  last_time: 0.1942  data_time: 0.0323  last_data_time: 0.0314   lr: 0.00014486  max_mem: 4083M
[07/16 17:40:24 d2.utils.events]:  eta: 7:33:41  iter: 599  total_loss: 0.6962  loss_cls: 0.2272  loss_box_reg: 0.3061  loss_rpn_cls: 0.02836  loss_rpn_loc: 0.1148    time: 0.6026  last_time: 0.1956  data_time: 0.0343  last_data_time: 0.0316   lr: 0.00014985  max_mem: 4083M
[07/16 17:40:28 d2.utils.events]:  eta: 7:27:31  iter: 619  total_loss: 0.7132  loss_cls: 0.238  loss_box_reg: 0.3342  loss_rpn_cls: 0.0273  loss_rpn_loc: 0.09835    time: 0.5894  last_time: 0.2204  data_time: 0.0350  last_data_time: 0.0585   lr: 0.00015485  max_mem: 4083M
[07/16 17:40:32 d2.utils.events]:  eta: 7:22:38  iter: 639  total_loss: 0.7224  loss_cls: 0.2522  loss_box_reg: 0.3114  loss_rpn_cls: 0.03136  loss_rpn_loc: 0.111    time: 0.5769  last_time: 0.1918  data_time: 0.0326  last_data_time: 0.0300   lr: 0.00015984  max_mem: 4083M
[07/16 17:40:36 d2.utils.events]:  eta: 7:12:43  iter: 659  total_loss: 0.6233  loss_cls: 0.2056  loss_box_reg: 0.2638  loss_rpn_cls: 0.0282  loss_rpn_loc: 0.09878    time: 0.5654  last_time: 0.1888  data_time: 0.0340  last_data_time: 0.0255   lr: 0.00016484  max_mem: 4083M
[07/16 17:40:39 d2.utils.events]:  eta: 7:07:09  iter: 679  total_loss: 0.6886  loss_cls: 0.2184  loss_box_reg: 0.2763  loss_rpn_cls: 0.03169  loss_rpn_loc: 0.09653    time: 0.5543  last_time: 0.1821  data_time: 0.0302  last_data_time: 0.0221   lr: 0.00016983  max_mem: 4083M
[07/16 17:40:43 d2.utils.events]:  eta: 6:58:47  iter: 699  total_loss: 0.6093  loss_cls: 0.2055  loss_box_reg: 0.2778  loss_rpn_cls: 0.0239  loss_rpn_loc: 0.08733    time: 0.5440  last_time: 0.1977  data_time: 0.0314  last_data_time: 0.0360   lr: 0.00017483  max_mem: 4083M
[07/16 17:40:47 d2.utils.events]:  eta: 6:53:12  iter: 719  total_loss: 0.6487  loss_cls: 0.2288  loss_box_reg: 0.2864  loss_rpn_cls: 0.02789  loss_rpn_loc: 0.1035    time: 0.5347  last_time: 0.1905  data_time: 0.0470  last_data_time: 0.0299   lr: 0.00017982  max_mem: 4083M
[07/16 17:40:51 d2.utils.events]:  eta: 6:46:55  iter: 739  total_loss: 0.6645  loss_cls: 0.2237  loss_box_reg: 0.3011  loss_rpn_cls: 0.02959  loss_rpn_loc: 0.09144    time: 0.5254  last_time: 0.1898  data_time: 0.0311  last_data_time: 0.0291   lr: 0.00018482  max_mem: 4083M
[07/16 17:40:55 d2.utils.events]:  eta: 6:37:53  iter: 759  total_loss: 0.7594  loss_cls: 0.2219  loss_box_reg: 0.279  loss_rpn_cls: 0.03779  loss_rpn_loc: 0.1017    time: 0.5167  last_time: 0.2115  data_time: 0.0328  last_data_time: 0.0504   lr: 0.00018981  max_mem: 4083M
[07/16 17:40:59 d2.utils.events]:  eta: 6:20:39  iter: 779  total_loss: 0.6859  loss_cls: 0.2088  loss_box_reg: 0.3035  loss_rpn_cls: 0.03145  loss_rpn_loc: 0.1237    time: 0.5084  last_time: 0.1924  data_time: 0.0328  last_data_time: 0.0299   lr: 0.00019481  max_mem: 4083M
[07/16 17:41:03 d2.utils.events]:  eta: 2:36:38  iter: 799  total_loss: 0.6348  loss_cls: 0.2205  loss_box_reg: 0.2701  loss_rpn_cls: 0.0251  loss_rpn_loc: 0.1132    time: 0.5005  last_time: 0.1903  data_time: 0.0325  last_data_time: 0.0305   lr: 0.0001998  max_mem: 4083M
[07/16 17:41:07 d2.utils.events]:  eta: 2:22:41  iter: 819  total_loss: 0.7089  loss_cls: 0.2246  loss_box_reg: 0.3096  loss_rpn_cls: 0.03571  loss_rpn_loc: 0.1335    time: 0.4930  last_time: 0.1961  data_time: 0.0317  last_data_time: 0.0330   lr: 0.0002048  max_mem: 4083M
[07/16 17:41:11 d2.utils.events]:  eta: 2:20:44  iter: 839  total_loss: 0.5459  loss_cls: 0.188  loss_box_reg: 0.2459  loss_rpn_cls: 0.02919  loss_rpn_loc: 0.08833    time: 0.4859  last_time: 0.1895  data_time: 0.0343  last_data_time: 0.0287   lr: 0.00020979  max_mem: 4083M
[07/16 17:41:15 d2.utils.events]:  eta: 2:19:01  iter: 859  total_loss: 0.6084  loss_cls: 0.1812  loss_box_reg: 0.2536  loss_rpn_cls: 0.02838  loss_rpn_loc: 0.1172    time: 0.4792  last_time: 0.1941  data_time: 0.0369  last_data_time: 0.0337   lr: 0.00021479  max_mem: 4083M
[07/16 17:41:19 d2.utils.events]:  eta: 2:17:32  iter: 879  total_loss: 0.6146  loss_cls: 0.1953  loss_box_reg: 0.2959  loss_rpn_cls: 0.03021  loss_rpn_loc: 0.08178    time: 0.4727  last_time: 0.1898  data_time: 0.0342  last_data_time: 0.0299   lr: 0.00021978  max_mem: 4083M
[07/16 17:41:22 d2.utils.events]:  eta: 2:16:03  iter: 899  total_loss: 0.5742  loss_cls: 0.1912  loss_box_reg: 0.279  loss_rpn_cls: 0.02832  loss_rpn_loc: 0.09243    time: 0.4665  last_time: 0.1893  data_time: 0.0310  last_data_time: 0.0268   lr: 0.00022478  max_mem: 4083M
[07/16 17:41:26 d2.utils.events]:  eta: 2:15:18  iter: 919  total_loss: 0.6397  loss_cls: 0.1966  loss_box_reg: 0.278  loss_rpn_cls: 0.02355  loss_rpn_loc: 0.08897    time: 0.4605  last_time: 0.1763  data_time: 0.0368  last_data_time: 0.0250   lr: 0.00022977  max_mem: 4083M
[07/16 17:41:30 d2.utils.events]:  eta: 2:14:28  iter: 939  total_loss: 0.558  loss_cls: 0.1748  loss_box_reg: 0.245  loss_rpn_cls: 0.02411  loss_rpn_loc: 0.0818    time: 0.4549  last_time: 0.2147  data_time: 0.0339  last_data_time: 0.0534   lr: 0.00023477  max_mem: 4083M
[07/16 17:41:34 d2.utils.events]:  eta: 2:13:35  iter: 959  total_loss: 0.5273  loss_cls: 0.1778  loss_box_reg: 0.2521  loss_rpn_cls: 0.02673  loss_rpn_loc: 0.08606    time: 0.4494  last_time: 0.1906  data_time: 0.0323  last_data_time: 0.0296   lr: 0.00023976  max_mem: 4083M
[07/16 17:41:38 d2.utils.events]:  eta: 2:12:51  iter: 979  total_loss: 0.6234  loss_cls: 0.1934  loss_box_reg: 0.2735  loss_rpn_cls: 0.03188  loss_rpn_loc: 0.1071    time: 0.4442  last_time: 0.1990  data_time: 0.0333  last_data_time: 0.0314   lr: 0.00024476  max_mem: 4083M
[07/16 17:41:42 d2.utils.events]:  eta: 2:12:36  iter: 999  total_loss: 0.5713  loss_cls: 0.1986  loss_box_reg: 0.2765  loss_rpn_cls: 0.02714  loss_rpn_loc: 0.08997    time: 0.4393  last_time: 0.1995  data_time: 0.0364  last_data_time: 0.0391   lr: 0.00024975  max_mem: 4083M
[07/16 17:41:46 d2.utils.events]:  eta: 2:11:13  iter: 1019  total_loss: 0.6272  loss_cls: 0.198  loss_box_reg: 0.2891  loss_rpn_cls: 0.02389  loss_rpn_loc: 0.1066    time: 0.4344  last_time: 0.1807  data_time: 0.0321  last_data_time: 0.0194   lr: 0.00025  max_mem: 4083M
[07/16 17:41:50 d2.utils.events]:  eta: 2:10:15  iter: 1039  total_loss: 0.5518  loss_cls: 0.175  loss_box_reg: 0.2528  loss_rpn_cls: 0.02385  loss_rpn_loc: 0.1106    time: 0.4298  last_time: 0.2011  data_time: 0.0322  last_data_time: 0.0382   lr: 0.00025  max_mem: 4083M
[07/16 17:41:54 d2.utils.events]:  eta: 2:09:56  iter: 1059  total_loss: 0.6349  loss_cls: 0.2061  loss_box_reg: 0.3067  loss_rpn_cls: 0.02311  loss_rpn_loc: 0.07342    time: 0.4253  last_time: 0.1879  data_time: 0.0318  last_data_time: 0.0253   lr: 0.00025  max_mem: 4083M
[07/16 17:41:58 d2.utils.events]:  eta: 2:09:21  iter: 1079  total_loss: 0.5974  loss_cls: 0.176  loss_box_reg: 0.2541  loss_rpn_cls: 0.027  loss_rpn_loc: 0.08756    time: 0.4211  last_time: 0.1909  data_time: 0.0344  last_data_time: 0.0300   lr: 0.00025  max_mem: 4083M
[07/16 17:42:01 d2.utils.events]:  eta: 2:09:08  iter: 1099  total_loss: 0.5947  loss_cls: 0.1833  loss_box_reg: 0.2476  loss_rpn_cls: 0.02222  loss_rpn_loc: 0.09275    time: 0.4170  last_time: 0.1859  data_time: 0.0348  last_data_time: 0.0249   lr: 0.00025  max_mem: 4083M
[07/16 17:42:05 d2.utils.events]:  eta: 2:08:44  iter: 1119  total_loss: 0.5662  loss_cls: 0.1833  loss_box_reg: 0.2525  loss_rpn_cls: 0.0225  loss_rpn_loc: 0.08477    time: 0.4130  last_time: 0.1917  data_time: 0.0322  last_data_time: 0.0312   lr: 0.00025  max_mem: 4083M
[07/16 17:42:09 d2.utils.events]:  eta: 2:08:25  iter: 1139  total_loss: 0.6456  loss_cls: 0.2016  loss_box_reg: 0.2582  loss_rpn_cls: 0.0295  loss_rpn_loc: 0.1061    time: 0.4092  last_time: 0.1829  data_time: 0.0327  last_data_time: 0.0216   lr: 0.00025  max_mem: 4083M
[07/16 17:42:13 d2.utils.events]:  eta: 2:08:03  iter: 1159  total_loss: 0.577  loss_cls: 0.1711  loss_box_reg: 0.23  loss_rpn_cls: 0.02813  loss_rpn_loc: 0.09807    time: 0.4054  last_time: 0.1762  data_time: 0.0316  last_data_time: 0.0263   lr: 0.00025  max_mem: 4083M
[07/16 17:42:17 d2.utils.events]:  eta: 2:07:49  iter: 1179  total_loss: 0.559  loss_cls: 0.1948  loss_box_reg: 0.2438  loss_rpn_cls: 0.02448  loss_rpn_loc: 0.09632    time: 0.4019  last_time: 0.1934  data_time: 0.0358  last_data_time: 0.0321   lr: 0.00025  max_mem: 4083M
[07/16 17:42:21 d2.utils.events]:  eta: 2:07:37  iter: 1199  total_loss: 0.5198  loss_cls: 0.1775  loss_box_reg: 0.2363  loss_rpn_cls: 0.02966  loss_rpn_loc: 0.07307    time: 0.3984  last_time: 0.1907  data_time: 0.0328  last_data_time: 0.0299   lr: 0.00025  max_mem: 4083M
[07/16 17:42:25 d2.utils.events]:  eta: 2:07:24  iter: 1219  total_loss: 0.6152  loss_cls: 0.1936  loss_box_reg: 0.2758  loss_rpn_cls: 0.02689  loss_rpn_loc: 0.1279    time: 0.3950  last_time: 0.1908  data_time: 0.0323  last_data_time: 0.0304   lr: 0.00025  max_mem: 4083M
[07/16 17:42:29 d2.utils.events]:  eta: 2:07:16  iter: 1239  total_loss: 0.5411  loss_cls: 0.1837  loss_box_reg: 0.2876  loss_rpn_cls: 0.02654  loss_rpn_loc: 0.07608    time: 0.3918  last_time: 0.2246  data_time: 0.0348  last_data_time: 0.0616   lr: 0.00025  max_mem: 4083M
[07/16 17:42:33 d2.utils.events]:  eta: 2:07:03  iter: 1259  total_loss: 0.5051  loss_cls: 0.1799  loss_box_reg: 0.2553  loss_rpn_cls: 0.02058  loss_rpn_loc: 0.07841    time: 0.3886  last_time: 0.1902  data_time: 0.0334  last_data_time: 0.0286   lr: 0.00025  max_mem: 4083M
[07/16 17:42:36 d2.utils.events]:  eta: 2:06:55  iter: 1279  total_loss: 0.5468  loss_cls: 0.1671  loss_box_reg: 0.274  loss_rpn_cls: 0.02248  loss_rpn_loc: 0.08837    time: 0.3856  last_time: 0.1976  data_time: 0.0319  last_data_time: 0.0359   lr: 0.00025  max_mem: 4083M
[07/16 17:42:40 d2.utils.events]:  eta: 2:06:45  iter: 1299  total_loss: 0.5742  loss_cls: 0.1919  loss_box_reg: 0.2584  loss_rpn_cls: 0.01857  loss_rpn_loc: 0.09018    time: 0.3827  last_time: 0.1967  data_time: 0.0331  last_data_time: 0.0351   lr: 0.00025  max_mem: 4083M
[07/16 17:42:44 d2.utils.events]:  eta: 2:06:34  iter: 1319  total_loss: 0.5485  loss_cls: 0.1614  loss_box_reg: 0.2545  loss_rpn_cls: 0.02361  loss_rpn_loc: 0.09214    time: 0.3799  last_time: 0.2069  data_time: 0.0330  last_data_time: 0.0448   lr: 0.00025  max_mem: 4083M
[07/16 17:42:48 d2.utils.events]:  eta: 2:06:21  iter: 1339  total_loss: 0.5382  loss_cls: 0.1694  loss_box_reg: 0.2212  loss_rpn_cls: 0.01813  loss_rpn_loc: 0.08453    time: 0.3770  last_time: 0.1945  data_time: 0.0303  last_data_time: 0.0327   lr: 0.00025  max_mem: 4083M
[07/16 17:42:52 d2.utils.events]:  eta: 2:06:13  iter: 1359  total_loss: 0.5898  loss_cls: 0.1809  loss_box_reg: 0.2575  loss_rpn_cls: 0.02091  loss_rpn_loc: 0.09104    time: 0.3743  last_time: 0.1942  data_time: 0.0327  last_data_time: 0.0288   lr: 0.00025  max_mem: 4083M
[07/16 17:42:56 d2.utils.events]:  eta: 2:06:04  iter: 1379  total_loss: 0.7027  loss_cls: 0.2148  loss_box_reg: 0.307  loss_rpn_cls: 0.0266  loss_rpn_loc: 0.1554    time: 0.3718  last_time: 0.1873  data_time: 0.0348  last_data_time: 0.0261   lr: 0.00025  max_mem: 4083M
[07/16 17:43:00 d2.utils.events]:  eta: 2:05:54  iter: 1399  total_loss: 0.5701  loss_cls: 0.1841  loss_box_reg: 0.2524  loss_rpn_cls: 0.01795  loss_rpn_loc: 0.1037    time: 0.3692  last_time: 0.1920  data_time: 0.0321  last_data_time: 0.0309   lr: 0.00025  max_mem: 4083M
[07/16 17:43:04 d2.utils.events]:  eta: 2:05:51  iter: 1419  total_loss: 0.5184  loss_cls: 0.166  loss_box_reg: 0.246  loss_rpn_cls: 0.02348  loss_rpn_loc: 0.09297    time: 0.3667  last_time: 0.1959  data_time: 0.0339  last_data_time: 0.0342   lr: 0.00025  max_mem: 4083M
[07/16 17:43:08 d2.utils.events]:  eta: 2:05:52  iter: 1439  total_loss: 0.5894  loss_cls: 0.1831  loss_box_reg: 0.2782  loss_rpn_cls: 0.0188  loss_rpn_loc: 0.0793    time: 0.3644  last_time: 0.1942  data_time: 0.0350  last_data_time: 0.0304   lr: 0.00025  max_mem: 4083M
[07/16 17:43:12 d2.utils.events]:  eta: 2:05:48  iter: 1459  total_loss: 0.5764  loss_cls: 0.1757  loss_box_reg: 0.2711  loss_rpn_cls: 0.02435  loss_rpn_loc: 0.106    time: 0.3620  last_time: 0.1943  data_time: 0.0329  last_data_time: 0.0300   lr: 0.00025  max_mem: 4083M

In [13]:
for file in sorted(OUTPUT_DIR.glob("*.pth")):
    print(file.name, f"{file.stat().st_size / 1e6:.1f} MB")

if (OUTPUT_DIR / "last_checkpoint").exists():
    print("\nlast_checkpoint content:")
    print((OUTPUT_DIR / "last_checkpoint").read_text())

model_0004999.pth 330.2 MB
model_0009999.pth 330.2 MB
model_0014999.pth 330.2 MB
model_0019999.pth 330.2 MB
model_0024999.pth 330.2 MB
model_0029999.pth 330.2 MB
model_0034999.pth 330.2 MB
model_0039999.pth 330.2 MB
model_best.pth 165.8 MB
model_final.pth 330.2 MB

last_checkpoint content:
model_best.pth

### **Evaluation with model_best**

In [14]:
BEST_MODEL = OUTPUT_DIR / "model_best.pth"

if BEST_MODEL.exists():
    cfg.MODEL.WEIGHTS = str(BEST_MODEL)
    print("Using best model:", BEST_MODEL)
else:
    cfg.MODEL.WEIGHTS = str(OUTPUT_DIR / "model_final.pth")
    print("Using final model instead.")

cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.5
predictor = DefaultPredictor(cfg)

Using best model: /content/drive/MyDrive/Dissertation/Runs/faster_rcnn/acdc_in_domain_faster_rcnn_seed456/model_best.pth
[07/16 20:04:05 d2.checkpoint.detection_checkpoint]: [DetectionCheckpointer] Loading from /content/drive/MyDrive/Dissertation/Runs/faster_rcnn/acdc_in_domain_faster_rcnn_seed456/model_best.pth ...

In [15]:
eval_datasets = {
    "global": "acdc_test",
    "fog": "acdc_test_fog",
    "rain": "acdc_test_rain",
    "snow": "acdc_test_snow",
}

results_rows = []

for condition, dataset_name in eval_datasets.items():
    print(f"\nEvaluating {condition.upper()}...")

    evaluator = COCOEvaluator(
        dataset_name,
        cfg,
        False,
        output_dir=str(OUTPUT_DIR / "evaluation" / condition)
    )

    loader = build_detection_test_loader(cfg, dataset_name)
    eval_results = inference_on_dataset(predictor.model, loader, evaluator)

    bbox = eval_results["bbox"]

    results_rows.append({
        "dataset": "ACDC",
        "model": "Faster R-CNN",
        "experiment": "in_domain",
        "seed": RANDOM_SEED,
        "condition": condition,
        "mAP50-95": bbox["AP"] / 100,
        "mAP50": bbox["AP50"] / 100,
        "mAP75": bbox["AP75"] / 100,
    })

results_df = pd.DataFrame(results_rows)
results_df

Evaluating GLOBAL...
WARNING [07/16 20:04:07 d2.evaluation.coco_evaluation]: COCO Evaluator instantiated using config, this is deprecated behavior. Please pass in explicit arguments instead.
[07/16 20:04:07 d2.evaluation.coco_evaluation]: Trying to convert 'acdc_test' to COCO format ...
[07/16 20:04:07 d2.data.datasets.coco]: Converting annotations of dataset 'acdc_test' to COCO format ...)
[07/16 20:04:08 d2.data.datasets.coco]: Converting dataset dicts into COCO format
[07/16 20:04:09 d2.data.datasets.coco]: Conversion finished, #images: 540, #annotations: 3358
[07/16 20:04:09 d2.data.datasets.coco]: Caching COCO format annotations at '/content/drive/MyDrive/Dissertation/Runs/faster_rcnn/acdc_in_domain_faster_rcnn_seed456/evaluation/global/acdc_test_coco_format.json' ...
[07/16 20:04:10 d2.data.build]: Distribution of instances among all 6 categories:
|  category  | #instances   |  category  | #instances   |  category  | #instances   |
|:----------:|:-------------|:----------:|:-------------|:----------:|:-------------|
|   person   | 556          |  bicycle   | 117          |    car     | 2342         |
| motorcycle | 77           |    bus     | 49           |   truck    | 217          |
|            |              |            |              |            |              |
|   total    | 3358         |            |              |            |              |
[07/16 20:04:10 d2.data.dataset_mapper]: [DatasetMapper] Augmentations used in inference: [ResizeShortestEdge(short_edge_length=(800, 800), max_size=1333, sample_style='choice')]
[07/16 20:04:10 d2.data.common]: Serializing the dataset using: <class 'detectron2.data.common._TorchSerializedList'>
[07/16 20:04:10 d2.data.common]: Serializing 540 elements to byte tensors and concatenating them all ...
[07/16 20:04:10 d2.data.common]: Serialized dataset takes 0.41 MiB
[07/16 20:04:10 d2.evaluation.evaluator]: Start inference on 540 batches
[07/16 20:04:12 d2.evaluation.evaluator]: Inference done 11/540. Dataloading: 0.1499 s/iter. Inference: 0.0302 s/iter. Eval: 0.0003 s/iter. Total: 0.1804 s/iter. ETA=0:01:35
[07/16 20:04:17 d2.evaluation.evaluator]: Inference done 37/540. Dataloading: 0.1650 s/iter. Inference: 0.0303 s/iter. Eval: 0.0003 s/iter. Total: 0.1957 s/iter. ETA=0:01:38
[07/16 20:04:22 d2.evaluation.evaluator]: Inference done 64/540. Dataloading: 0.1609 s/iter. Inference: 0.0303 s/iter. Eval: 0.0003 s/iter. Total: 0.1916 s/iter. ETA=0:01:31
[07/16 20:04:28 d2.evaluation.evaluator]: Inference done 90/540. Dataloading: 0.1632 s/iter. Inference: 0.0303 s/iter. Eval: 0.0003 s/iter. Total: 0.1939 s/iter. ETA=0:01:27
[07/16 20:04:33 d2.evaluation.evaluator]: Inference done 115/540. Dataloading: 0.1677 s/iter. Inference: 0.0303 s/iter. Eval: 0.0003 s/iter. Total: 0.1984 s/iter. ETA=0:01:24
[07/16 20:04:38 d2.evaluation.evaluator]: Inference done 145/540. Dataloading: 0.1641 s/iter. Inference: 0.0304 s/iter. Eval: 0.0003 s/iter. Total: 0.1948 s/iter. ETA=0:01:16
[07/16 20:04:44 d2.evaluation.evaluator]: Inference done 173/540. Dataloading: 0.1626 s/iter. Inference: 0.0303 s/iter. Eval: 0.0003 s/iter. Total: 0.1933 s/iter. ETA=0:01:10
[07/16 20:04:49 d2.evaluation.evaluator]: Inference done 200/540. Dataloading: 0.1628 s/iter. Inference: 0.0303 s/iter. Eval: 0.0003 s/iter. Total: 0.1935 s/iter. ETA=0:01:05
[07/16 20:04:54 d2.evaluation.evaluator]: Inference done 225/540. Dataloading: 0.1643 s/iter. Inference: 0.0303 s/iter. Eval: 0.0003 s/iter. Total: 0.1950 s/iter. ETA=0:01:01
[07/16 20:04:59 d2.evaluation.evaluator]: Inference done 253/540. Dataloading: 0.1636 s/iter. Inference: 0.0303 s/iter. Eval: 0.0003 s/iter. Total: 0.1943 s/iter. ETA=0:00:55
[07/16 20:05:04 d2.evaluation.evaluator]: Inference done 281/540. Dataloading: 0.1622 s/iter. Inference: 0.0303 s/iter. Eval: 0.0003 s/iter. Total: 0.1928 s/iter. ETA=0:00:49
[07/16 20:05:10 d2.evaluation.evaluator]: Inference done 309/540. Dataloading: 0.1617 s/iter. Inference: 0.0303 s/iter. Eval: 0.0003 s/iter. Total: 0.1924 s/iter. ETA=0:00:44
[07/16 20:05:15 d2.evaluation.evaluator]: Inference done 336/540. Dataloading: 0.1615 s/iter. Inference: 0.0303 s/iter. Eval: 0.0003 s/iter. Total: 0.1921 s/iter. ETA=0:00:39
[07/16 20:05:20 d2.evaluation.evaluator]: Inference done 367/540. Dataloading: 0.1592 s/iter. Inference: 0.0303 s/iter. Eval: 0.0003 s/iter. Total: 0.1898 s/iter. ETA=0:00:32
[07/16 20:05:25 d2.evaluation.evaluator]: Inference done 396/540. Dataloading: 0.1583 s/iter. Inference: 0.0303 s/iter. Eval: 0.0003 s/iter. Total: 0.1889 s/iter. ETA=0:00:27
[07/16 20:05:30 d2.evaluation.evaluator]: Inference done 426/540. Dataloading: 0.1569 s/iter. Inference: 0.0303 s/iter. Eval: 0.0003 s/iter. Total: 0.1875 s/iter. ETA=0:00:21
[07/16 20:05:35 d2.evaluation.evaluator]: Inference done 454/540. Dataloading: 0.1554 s/iter. Inference: 0.0314 s/iter. Eval: 0.0003 s/iter. Total: 0.1871 s/iter. ETA=0:00:16
[07/16 20:05:40 d2.evaluation.evaluator]: Inference done 478/540. Dataloading: 0.1569 s/iter. Inference: 0.0314 s/iter. Eval: 0.0003 s/iter. Total: 0.1886 s/iter. ETA=0:00:11
[07/16 20:05:46 d2.evaluation.evaluator]: Inference done 507/540. Dataloading: 0.1566 s/iter. Inference: 0.0313 s/iter. Eval: 0.0003 s/iter. Total: 0.1883 s/iter. ETA=0:00:06
[07/16 20:05:51 d2.evaluation.evaluator]: Inference done 537/540. Dataloading: 0.1559 s/iter. Inference: 0.0313 s/iter. Eval: 0.0003 s/iter. Total: 0.1875 s/iter. ETA=0:00:00
[07/16 20:05:51 d2.evaluation.evaluator]: Total inference time: 0:01:40.250591 (0.187384 s / iter per device, on 1 devices)
[07/16 20:05:51 d2.evaluation.evaluator]: Total inference pure compute time: 0:00:16 (0.031251 s / iter per device, on 1 devices)
[07/16 20:05:51 d2.evaluation.coco_evaluation]: Preparing results for COCO format ...
[07/16 20:05:51 d2.evaluation.coco_evaluation]: Saving results to /content/drive/MyDrive/Dissertation/Runs/faster_rcnn/acdc_in_domain_faster_rcnn_seed456/evaluation/global/coco_instances_results.json
[07/16 20:05:51 d2.evaluation.coco_evaluation]: Evaluating predictions with unofficial COCO API...
Loading and preparing results...
DONE (t=0.00s)
creating index...
index created!
[07/16 20:05:51 d2.evaluation.fast_eval_api]: Evaluate annotation type *bbox*
[07/16 20:05:51 d2.evaluation.fast_eval_api]: COCOeval_opt.evaluate() finished in 0.09 seconds.
[07/16 20:05:51 d2.evaluation.fast_eval_api]: Accumulating evaluation results...
[07/16 20:05:51 d2.evaluation.fast_eval_api]: COCOeval_opt.accumulate() finished in 0.03 seconds.
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.416
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.597
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.449
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.185
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.451
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.618
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.302
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.463
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.465
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.235
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.499
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.665
[07/16 20:05:51 d2.evaluation.coco_evaluation]: Evaluation results for bbox:
|   AP   |  AP50  |  AP75  |  APs   |  APm   |  APl   |
|:------:|:------:|:------:|:------:|:------:|:------:|
| 41.633 | 59.732 | 44.892 | 18.473 | 45.145 | 61.750 |
[07/16 20:05:51 d2.evaluation.coco_evaluation]: Per-category bbox AP:
| category   | AP     | category   | AP     | category   | AP     |
|:-----------|:-------|:-----------|:-------|:-----------|:-------|
| person     | 40.844 | bicycle    | 28.608 | car        | 57.360 |
| motorcycle | 24.785 | bus        | 42.615 | truck      | 55.587 |

Evaluating FOG...
WARNING [07/16 20:05:51 d2.evaluation.coco_evaluation]: COCO Evaluator instantiated using config, this is deprecated behavior. Please pass in explicit arguments instead.
[07/16 20:05:51 d2.evaluation.coco_evaluation]: Trying to convert 'acdc_test_fog' to COCO format ...
[07/16 20:05:52 d2.data.datasets.coco]: Converting annotations of dataset 'acdc_test_fog' to COCO format ...)
[07/16 20:05:52 d2.data.datasets.coco]: Converting dataset dicts into COCO format
[07/16 20:05:52 d2.data.datasets.coco]: Conversion finished, #images: 100, #annotations: 578
[07/16 20:05:52 d2.data.datasets.coco]: Caching COCO format annotations at '/content/drive/MyDrive/Dissertation/Runs/faster_rcnn/acdc_in_domain_faster_rcnn_seed456/evaluation/fog/acdc_test_fog_coco_format.json' ...
[07/16 20:05:52 d2.data.build]: Distribution of instances among all 6 categories:
|  category  | #instances   |  category  | #instances   |  category  | #instances   |
|:----------:|:-------------|:----------:|:-------------|:----------:|:-------------|
|   person   | 52           |  bicycle   | 13           |    car     | 408          |
| motorcycle | 7            |    bus     | 7            |   truck    | 91           |
|            |              |            |              |            |              |
|   total    | 578          |            |              |            |              |
[07/16 20:05:52 d2.data.dataset_mapper]: [DatasetMapper] Augmentations used in inference: [ResizeShortestEdge(short_edge_length=(800, 800), max_size=1333, sample_style='choice')]
[07/16 20:05:52 d2.data.common]: Serializing the dataset using: <class 'detectron2.data.common._TorchSerializedList'>
[07/16 20:05:52 d2.data.common]: Serializing 100 elements to byte tensors and concatenating them all ...
[07/16 20:05:52 d2.data.common]: Serialized dataset takes 0.07 MiB
[07/16 20:05:52 d2.evaluation.evaluator]: Start inference on 100 batches
[07/16 20:05:56 d2.evaluation.evaluator]: Inference done 83/100. Dataloading: 0.0157 s/iter. Inference: 0.0280 s/iter. Eval: 0.0003 s/iter. Total: 0.0440 s/iter. ETA=0:00:00
[07/16 20:05:57 d2.evaluation.evaluator]: Total inference time: 0:00:04.198438 (0.044194 s / iter per device, on 1 devices)
[07/16 20:05:57 d2.evaluation.evaluator]: Total inference pure compute time: 0:00:02 (0.027925 s / iter per device, on 1 devices)
[07/16 20:05:57 d2.evaluation.coco_evaluation]: Preparing results for COCO format ...
[07/16 20:05:57 d2.evaluation.coco_evaluation]: Saving results to /content/drive/MyDrive/Dissertation/Runs/faster_rcnn/acdc_in_domain_faster_rcnn_seed456/evaluation/fog/coco_instances_results.json
[07/16 20:05:57 d2.evaluation.coco_evaluation]: Evaluating predictions with unofficial COCO API...
Loading and preparing results...
DONE (t=0.00s)
creating index...
index created!
[07/16 20:05:57 d2.evaluation.fast_eval_api]: Evaluate annotation type *bbox*
[07/16 20:05:57 d2.evaluation.fast_eval_api]: COCOeval_opt.evaluate() finished in 0.02 seconds.
[07/16 20:05:57 d2.evaluation.fast_eval_api]: Accumulating evaluation results...
[07/16 20:05:57 d2.evaluation.fast_eval_api]: COCOeval_opt.accumulate() finished in 0.02 seconds.
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.552
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.727
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.584
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.223
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.623
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.815
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.424
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.583
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.585
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.248
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.652
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.851
[07/16 20:05:57 d2.evaluation.coco_evaluation]: Evaluation results for bbox:
|   AP   |  AP50  |  AP75  |  APs   |  APm   |  APl   |
|:------:|:------:|:------:|:------:|:------:|:------:|
| 55.202 | 72.663 | 58.410 | 22.252 | 62.325 | 81.451 |
[07/16 20:05:57 d2.evaluation.coco_evaluation]: Per-category bbox AP:
| category   | AP     | category   | AP     | category   | AP     |
|:-----------|:-------|:-----------|:-------|:-----------|:-------|
| person     | 41.467 | bicycle    | 40.561 | car        | 62.958 |
| motorcycle | 56.762 | bus        | 68.416 | truck      | 61.047 |

Evaluating RAIN...
WARNING [07/16 20:05:57 d2.evaluation.coco_evaluation]: COCO Evaluator instantiated using config, this is deprecated behavior. Please pass in explicit arguments instead.
[07/16 20:05:57 d2.evaluation.coco_evaluation]: Trying to convert 'acdc_test_rain' to COCO format ...
[07/16 20:05:57 d2.data.datasets.coco]: Converting annotations of dataset 'acdc_test_rain' to COCO format ...)
[07/16 20:05:57 d2.data.datasets.coco]: Converting dataset dicts into COCO format
[07/16 20:05:58 d2.data.datasets.coco]: Conversion finished, #images: 340, #annotations: 2082
[07/16 20:05:58 d2.data.datasets.coco]: Caching COCO format annotations at '/content/drive/MyDrive/Dissertation/Runs/faster_rcnn/acdc_in_domain_faster_rcnn_seed456/evaluation/rain/acdc_test_rain_coco_format.json' ...
[07/16 20:05:58 d2.data.build]: Distribution of instances among all 6 categories:
|  category  | #instances   |  category  | #instances   |  category  | #instances   |
|:----------:|:-------------|:----------:|:-------------|:----------:|:-------------|
|   person   | 356          |  bicycle   | 79           |    car     | 1456         |
| motorcycle | 65           |    bus     | 31           |   truck    | 95           |
|            |              |            |              |            |              |
|   total    | 2082         |            |              |            |              |
[07/16 20:05:58 d2.data.dataset_mapper]: [DatasetMapper] Augmentations used in inference: [ResizeShortestEdge(short_edge_length=(800, 800), max_size=1333, sample_style='choice')]
[07/16 20:05:58 d2.data.common]: Serializing the dataset using: <class 'detectron2.data.common._TorchSerializedList'>
[07/16 20:05:58 d2.data.common]: Serializing 340 elements to byte tensors and concatenating them all ...
[07/16 20:05:59 d2.data.common]: Serialized dataset takes 0.25 MiB
[07/16 20:05:59 d2.evaluation.evaluator]: Start inference on 340 batches
[07/16 20:06:01 d2.evaluation.evaluator]: Inference done 48/340. Dataloading: 0.0157 s/iter. Inference: 0.0290 s/iter. Eval: 0.0003 s/iter. Total: 0.0450 s/iter. ETA=0:00:13
[07/16 20:06:06 d2.evaluation.evaluator]: Inference done 161/340. Dataloading: 0.0154 s/iter. Inference: 0.0287 s/iter. Eval: 0.0003 s/iter. Total: 0.0445 s/iter. ETA=0:00:07
[07/16 20:06:11 d2.evaluation.evaluator]: Inference done 274/340. Dataloading: 0.0157 s/iter. Inference: 0.0284 s/iter. Eval: 0.0003 s/iter. Total: 0.0444 s/iter. ETA=0:00:02
[07/16 20:06:14 d2.evaluation.evaluator]: Total inference time: 0:00:14.949419 (0.044625 s / iter per device, on 1 devices)
[07/16 20:06:14 d2.evaluation.evaluator]: Total inference pure compute time: 0:00:09 (0.028424 s / iter per device, on 1 devices)
[07/16 20:06:14 d2.evaluation.coco_evaluation]: Preparing results for COCO format ...
[07/16 20:06:14 d2.evaluation.coco_evaluation]: Saving results to /content/drive/MyDrive/Dissertation/Runs/faster_rcnn/acdc_in_domain_faster_rcnn_seed456/evaluation/rain/coco_instances_results.json
[07/16 20:06:14 d2.evaluation.coco_evaluation]: Evaluating predictions with unofficial COCO API...
Loading and preparing results...
DONE (t=0.00s)
creating index...
index created!
[07/16 20:06:14 d2.evaluation.fast_eval_api]: Evaluate annotation type *bbox*
[07/16 20:06:14 d2.evaluation.fast_eval_api]: COCOeval_opt.evaluate() finished in 0.06 seconds.
[07/16 20:06:14 d2.evaluation.fast_eval_api]: Accumulating evaluation results...
[07/16 20:06:14 d2.evaluation.fast_eval_api]: COCOeval_opt.accumulate() finished in 0.02 seconds.
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.363
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.531
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.388
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.150
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.387
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.582
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.264
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.407
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.409
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.186
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.440
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.628
[07/16 20:06:14 d2.evaluation.coco_evaluation]: Evaluation results for bbox:
|   AP   |  AP50  |  AP75  |  APs   |  APm   |  APl   |
|:------:|:------:|:------:|:------:|:------:|:------:|
| 36.260 | 53.111 | 38.845 | 15.025 | 38.685 | 58.207 |
[07/16 20:06:14 d2.evaluation.coco_evaluation]: Per-category bbox AP:
| category   | AP     | category   | AP     | category   | AP     |
|:-----------|:-------|:-----------|:-------|:-----------|:-------|
| person     | 37.009 | bicycle    | 19.673 | car        | 54.090 |
| motorcycle | 21.173 | bus        | 31.991 | truck      | 53.625 |

Evaluating SNOW...
WARNING [07/16 20:06:14 d2.evaluation.coco_evaluation]: COCO Evaluator instantiated using config, this is deprecated behavior. Please pass in explicit arguments instead.
[07/16 20:06:14 d2.evaluation.coco_evaluation]: Trying to convert 'acdc_test_snow' to COCO format ...
[07/16 20:06:14 d2.data.datasets.coco]: Converting annotations of dataset 'acdc_test_snow' to COCO format ...)
[07/16 20:06:14 d2.data.datasets.coco]: Converting dataset dicts into COCO format
[07/16 20:06:14 d2.data.datasets.coco]: Conversion finished, #images: 100, #annotations: 698
[07/16 20:06:14 d2.data.datasets.coco]: Caching COCO format annotations at '/content/drive/MyDrive/Dissertation/Runs/faster_rcnn/acdc_in_domain_faster_rcnn_seed456/evaluation/snow/acdc_test_snow_coco_format.json' ...
[07/16 20:06:15 d2.data.build]: Distribution of instances among all 6 categories:
|  category  | #instances   |  category  | #instances   |  category  | #instances   |
|:----------:|:-------------|:----------:|:-------------|:----------:|:-------------|
|   person   | 148          |  bicycle   | 25           |    car     | 478          |
| motorcycle | 5            |    bus     | 11           |   truck    | 31           |
|            |              |            |              |            |              |
|   total    | 698          |            |              |            |              |
[07/16 20:06:15 d2.data.dataset_mapper]: [DatasetMapper] Augmentations used in inference: [ResizeShortestEdge(short_edge_length=(800, 800), max_size=1333, sample_style='choice')]
[07/16 20:06:15 d2.data.common]: Serializing the dataset using: <class 'detectron2.data.common._TorchSerializedList'>
[07/16 20:06:15 d2.data.common]: Serializing 100 elements to byte tensors and concatenating them all ...
[07/16 20:06:15 d2.data.common]: Serialized dataset takes 0.08 MiB
[07/16 20:06:15 d2.evaluation.evaluator]: Start inference on 100 batches
[07/16 20:06:16 d2.evaluation.evaluator]: Inference done 25/100. Dataloading: 0.0153 s/iter. Inference: 0.0280 s/iter. Eval: 0.0003 s/iter. Total: 0.0436 s/iter. ETA=0:00:03

,dataset,model,experiment,seed,condition,mAP50-95,mAP50,mAP75
0,ACDC,Faster R-CNN,in_domain,456,global,0.416332,0.597323,0.448921
1,ACDC,Faster R-CNN,in_domain,456,fog,0.552021,0.726634,0.584098
2,ACDC,Faster R-CNN,in_domain,456,rain,0.362602,0.531106,0.388452
3,ACDC,Faster R-CNN,in_domain,456,snow,0.497758,0.693990,0.557561

### **FPS**

In [ ]:
def get_image_paths_from_split(voc_root, split_name):
    split_file = voc_root / "ImageSets" / "Main" / f"{split_name}.txt"

    with open(split_file, "r") as f:
        image_ids = [line.strip() for line in f if line.strip()]

    return [
        voc_root / "JPEGImages" / f"{image_id}.jpg"
        for image_id in image_ids
        if (voc_root / "JPEGImages" / f"{image_id}.jpg").exists()
    ]


def measure_fps(predictor, image_paths, warmup=20):
    images = []

    for p in image_paths:
        img = cv2.imread(str(p))
        if img is not None:
            images.append(img)

    for img in images[:warmup]:
        _ = predictor(img)

    if torch.cuda.is_available():
        torch.cuda.synchronize()

    times = []

    for img in images:
        start = time.perf_counter()
        _ = predictor(img)

        if torch.cuda.is_available():
            torch.cuda.synchronize()

        end = time.perf_counter()
        times.append(end - start)

    avg_ms = np.mean(times) * 1000
    fps = 1000 / avg_ms

    return avg_ms, fps

In [ ]:
split_mapping = {
    "global": "test",
    "fog": "test_fog",
    "rain": "test_rain",
    "snow": "test_snow",
}

for idx, row in results_df.iterrows():
    condition = row["condition"]
    split_name = split_mapping[condition]

    image_paths = get_image_paths_from_split(ACDC_VOC_ROOT, split_name)

    inference_ms, fps = measure_fps(
        predictor,
        image_paths,
        warmup=20
    )

    results_df.loc[idx, "Inference_ms_per_image"] = inference_ms
    results_df.loc[idx, "FPS"] = fps

results_df

,dataset,model,experiment,seed,condition,mAP50-95,mAP50,mAP75,Inference_ms_per_image,FPS
0,ACDC,Faster R-CNN,in_domain,123,global,0.428254,0.612108,0.455618,61.770184,16.189040
1,ACDC,Faster R-CNN,in_domain,123,fog,0.572156,0.764261,0.621466,61.786938,16.184651
2,ACDC,Faster R-CNN,in_domain,123,rain,0.374499,0.544613,0.388124,60.997793,16.394036
3,ACDC,Faster R-CNN,in_domain,123,snow,0.515350,0.697251,0.567666,61.904689,16.153865

### **Save results**

In [ ]:
results_csv = OUTPUT_DIR / "acdc_faster_rcnn_in_domain_results_summary.csv"
results_json = OUTPUT_DIR / "acdc_faster_rcnn_in_domain_results_summary.json"

results_df.to_csv(results_csv, index=False)

with open(results_json, "w") as f:
    json.dump(results_df.to_dict(orient="records"), f, indent=4)

print("Saved:")
print(results_csv)
print(results_json)

Saved:
/content/drive/MyDrive/Dissertation/Runs/faster_rcnn/acdc_in_domain_faster_rcnn_seed123/acdc_faster_rcnn_in_domain_results_summary.csv
/content/drive/MyDrive/Dissertation/Runs/faster_rcnn/acdc_in_domain_faster_rcnn_seed123/acdc_faster_rcnn_in_domain_results_summary.json